// isls-multilang/src/backends/docs_backend.rs
//
// DocsBackend: README from IR root node, module docs from Function nodes,
//              API docs from interface edges.
// Fully deterministic — no Oracle needed.

use std::collections::BTreeMap;
use crate::codegen::{CodegenBackend, EmittedFile, ScaffoldFile, count_lines};
use crate::glyph_ir::IrDocument;

pub struct DocsBackend;

impl CodegenBackend for DocsBackend {
    fn language(&self) -> &str { "markdown" }
    fn extension(&self) -> &str { "md" }
    fn needs_oracle(&self) -> bool { false }

    fn scaffold(&self, doc: &IrDocument) -> Vec<ScaffoldFile> {
        // README from domain + root node
        let module_list: String = doc.function_nodes()
            .iter()
            .map(|n| {
                let desc = n.description().unwrap_or("—");
                format!("- **{}**: {}", n.name, desc)
            })
            .collect::<Vec<_>>()
            .join("\n");

        let readme_content = format!(
            "# {}\n\nGenerated by isls-multilang DocsBackend.\n\n## Modules\n\n{}\n\n## Interfaces\n\n{} interface(s) defined.\n",
            doc.domain,
            if module_list.is_empty() { "No modules.".to_string() } else { module_list },
            doc.callee_edges().len()
        );

        // API docs from function nodes
        let api_sections: Vec<String> = doc.function_nodes()
            .iter()
            .map(|n| {
                let desc = n.description().unwrap_or("No description.");
                let deps = n.params.as_deref().unwrap_or(&[]);
                let deps_str = if deps.is_empty() {
                    "None".to_string()
                } else {
                    deps.join(", ")
                };
                format!("### {}\n\n{}\n\n**Dependencies:** {}\n", n.name, desc, deps_str)
            })
            .collect();

        let api_doc = format!("# API Reference\n\n{}", api_sections.join("\n"));

        vec![
            ScaffoldFile {
                path: "README.md".to_string(),
                language: "markdown".to_string(),
                imports: vec![],
                type_definitions: vec![readme_content],
                function_stubs: vec![],
            },
            ScaffoldFile {
                path: "docs/API.md".to_string(),
                language: "markdown".to_string(),
                imports: vec![],
                type_definitions: vec![api_doc],
                function_stubs: vec![],
            },
        ]
    }

    fn assemble(
        &self,
        scaffolds: &[ScaffoldFile],
        _oracle_bodies: &BTreeMap<String, String>,
    ) -> Vec<EmittedFile> {
        scaffolds.iter().map(|s| {
            let content = s.type_definitions.join("\n\n");
            EmittedFile {
                path: s.path.clone(),
                content: content.clone(),
                language: s.language.clone(),
                scaffold_lines: count_lines(&content),
                oracle_lines: 0,
            }
        }).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::glyph_ir::{IrDocument, IrNode, IrEdge, NodeKind, EdgeKind};
    use std::collections::BTreeMap as BM;
    use serde_json::json;

    fn make_doc() -> IrDocument {
        let mut doc = IrDocument::new("my-service", "test-id");
        let root = IrNode::new("n_root", NodeKind::Module, "root");
        let mut fn_node = IrNode::new("n_fn_0", NodeKind::Function, "AuthModule");
        let mut props = BM::new();
        props.insert("description".into(), json!("Handles authentication"));
        fn_node.properties = Some(props);
        doc.nodes.push(root);
        doc.nodes.push(fn_node);
        doc.edges.push(IrEdge::new("n_root", "n_fn_0", EdgeKind::Contains));
        doc.canonicalize();
        doc
    }

    // AT-BB11: Generate README from IR; verify contains module names and descriptions.
    #[test]
    fn at_bb11_docs_backend() {
        let backend = DocsBackend;
        let doc = make_doc();
        let scaffolds = backend.scaffold(&doc);
        let files = backend.assemble(&scaffolds, &BTreeMap::new());
        assert!(!files.is_empty(), "AT-BB11: must produce doc files");
        let readme = files.iter().find(|f| f.path == "README.md").expect("README.md");
        assert!(readme.content.contains("my-service"), "AT-BB11: README must contain domain name");
        assert!(readme.content.contains("AuthModule"), "AT-BB11: README must contain module name");
        assert_eq!(readme.oracle_lines, 0, "AT-BB11: docs backend should have zero oracle lines");
    }
}
