// isls-multilang/src/backends/python_backend.rs
//
// PythonBackend: @dataclass class for types, def signatures with type hints,
//                import from IR edges, requirements.txt.

use std::collections::BTreeMap;
use crate::codegen::{CodegenBackend, EmittedFile, FunctionStub, ScaffoldFile, count_lines};
use crate::glyph_ir::IrDocument;

pub struct PythonBackend;

impl CodegenBackend for PythonBackend {
    fn language(&self) -> &str { "python" }
    fn extension(&self) -> &str { "py" }

    fn scaffold(&self, doc: &IrDocument) -> Vec<ScaffoldFile> {
        let imports: Vec<String> = {
            let mut imps = vec![
                "from __future__ import annotations".to_string(),
                "from dataclasses import dataclass".to_string(),
                "from typing import Optional".to_string(),
            ];
            for edge in doc.callee_edges() {
                if let Some(to_node) = doc.nodes.iter().find(|n| n.id == edge.to) {
                    imps.push(format!("from .{} import {}", to_snake_case(&to_node.name), to_pascal_case(&to_node.name)));
                }
            }
            imps
        };

        let type_defs: Vec<String> = doc.function_nodes()
            .iter()
            .filter(|n| n.kind_prop().unwrap_or("function") == "type")
            .map(|n| {
                let fields = n.params.as_deref().unwrap_or(&[])
                    .iter()
                    .map(|f| {
                        let parts: Vec<&str> = f.splitn(2, ':').collect();
                        if parts.len() == 2 {
                            format!("    {}: {}", parts[0].trim(), map_py_type(parts[1].trim()))
                        } else {
                            format!("    {}: str", f.trim())
                        }
                    })
                    .collect::<Vec<_>>()
                    .join("\n");
                format!(
                    "@dataclass\nclass {}:\n{}",
                    to_pascal_case(&n.name),
                    if fields.is_empty() { "    pass".to_string() } else { fields }
                )
            })
            .collect();

        let stubs: Vec<FunctionStub> = doc.function_nodes()
            .iter()
            .filter(|n| n.kind_prop().unwrap_or("function") != "type")
            .map(|n| {
                let placeholder = format!("# ORACLE_BODY_{}", n.id);
                FunctionStub {
                    node_id: n.id.clone(),
                    name: to_snake_case(&n.name),
                    signature: format!("def {}() -> str", to_snake_case(&n.name)),
                    body_placeholder: placeholder,
                }
            })
            .collect();

        vec![ScaffoldFile {
            path: "src/main.py".to_string(),
            language: "python".to_string(),
            imports,
            type_definitions: type_defs,
            function_stubs: stubs,
        }]
    }

    fn assemble(
        &self,
        scaffolds: &[ScaffoldFile],
        oracle_bodies: &BTreeMap<String, String>,
    ) -> Vec<EmittedFile> {
        let mut emitted = Vec::new();

        for scaffold in scaffolds {
            let mut content = String::new();
            content.push_str("# Generated by isls-multilang PythonBackend\n\n");

            for imp in &scaffold.imports {
                content.push_str(imp);
                content.push('\n');
            }
            content.push('\n');

            for td in &scaffold.type_definitions {
                content.push_str(td);
                content.push_str("\n\n");
            }

            let scaffold_base = count_lines(&content);
            let mut oracle_lines = 0;

            for stub in &scaffold.function_stubs {
                content.push_str(&format!("{}:\n", stub.signature));
                if let Some(body) = oracle_bodies.get(&stub.node_id) {
                    let indented = indent_body(body, 4);
                    oracle_lines += count_lines(&indented);
                    content.push_str(&indented);
                } else {
                    content.push_str(&format!("    {}\n", stub.body_placeholder));
                    content.push_str("    raise NotImplementedError('Oracle body not provided')\n");
                }
                content.push('\n');
            }

            emitted.push(EmittedFile {
                path: scaffold.path.clone(),
                content: content.clone(),
                language: "python".to_string(),
                scaffold_lines: scaffold_base,
                oracle_lines,
            });
        }

        // requirements.txt
        let reqs = "# Generated requirements\n";
        emitted.push(EmittedFile {
            path: "requirements.txt".to_string(),
            content: reqs.to_string(),
            language: "text".to_string(),
            scaffold_lines: count_lines(reqs),
            oracle_lines: 0,
        });

        emitted
    }
}

fn to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 { out.push('_'); }
        out.push(ch.to_lowercase().next().unwrap_or(ch));
    }
    out.replace(['-', ' '], "_")
}

fn to_pascal_case(s: &str) -> String {
    s.split(['_', '-', ' '])
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn map_py_type(t: &str) -> &str {
    match t.trim() {
        "i64" | "i32" | "i8" | "usize" => "int",
        "f64" | "f32" => "float",
        "bool" => "bool",
        "String" | "string" | "str" => "str",
        _ => "str",
    }
}

fn indent_body(body: &str, spaces: usize) -> String {
    let indent = " ".repeat(spaces);
    body.lines()
        .map(|line| if line.is_empty() { String::new() } else { format!("{}{}", indent, line) })
        .collect::<Vec<_>>()
        .join("\n")
        + "\n"
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::glyph_ir::{IrDocument, IrNode, IrEdge, NodeKind, EdgeKind};
    use std::collections::BTreeMap as BM;
    use serde_json::json;

    // AT-BB6: verify .py files with correct @dataclass definitions.
    #[test]
    fn at_bb6_python_scaffold() {
        let mut doc = IrDocument::new("test", "test-id");
        let root = IrNode::new("n_root", NodeKind::Module, "root");
        let mut type_node = IrNode::new("n_type_user", NodeKind::Function, "User");
        type_node.params = Some(vec!["id:i64".into(), "name:String".into()]);
        let mut props = BM::new();
        props.insert("kind".into(), json!("type"));
        type_node.properties = Some(props);
        doc.nodes.push(root);
        doc.nodes.push(type_node);
        doc.edges.push(IrEdge::new("n_root", "n_type_user", EdgeKind::Contains));
        doc.canonicalize();

        let backend = PythonBackend;
        let scaffolds = backend.scaffold(&doc);
        assert!(!scaffolds.is_empty(), "AT-BB6: must have scaffold files");
        let main = scaffolds.iter().find(|f| f.path.contains(".py")).expect("main.py");
        assert!(main.type_definitions.iter().any(|td| td.contains("@dataclass")),
            "AT-BB6: must have @dataclass");
        assert!(main.type_definitions.iter().any(|td| td.contains("class User")),
            "AT-BB6: must have 'class User'");
    }
}
