// isls-multilang/src/backends/rust_backend.rs
//
// RustBackend: generates Rust scaffolding from glyph-ir structure.
// Scaffolding: mod declarations, pub struct with fields, pub fn signatures,
//              use imports from IR edges, Cargo.toml.

use std::collections::BTreeMap;
use crate::codegen::{CodegenBackend, EmittedFile, FunctionStub, ScaffoldFile, count_lines};
use crate::glyph_ir::IrDocument;

pub struct RustBackend;

impl CodegenBackend for RustBackend {
    fn language(&self) -> &str { "rust" }
    fn extension(&self) -> &str { "rs" }

    fn scaffold(&self, doc: &IrDocument) -> Vec<ScaffoldFile> {
        let mut files: Vec<ScaffoldFile> = Vec::new();

        // Collect imports from CalleeRef edges
        let imports: Vec<String> = doc.callee_edges()
            .iter()
            .filter_map(|e| {
                let to_node = doc.nodes.iter().find(|n| n.id == e.to)?;
                Some(format!("use crate::{};", to_rust_module_name(&to_node.name)))
            })
            .collect::<std::collections::HashSet<_>>()
            .into_iter()
            .collect();

        // Type definitions from nodes with kind_prop == "type"
        let type_defs: Vec<String> = doc.function_nodes()
            .iter()
            .filter(|n| n.kind_prop().unwrap_or("function") == "type")
            .map(|n| {
                let fields = n.params.as_deref().unwrap_or(&[])
                    .iter()
                    .map(|f| {
                        let parts: Vec<&str> = f.splitn(2, ':').collect();
                        if parts.len() == 2 {
                            format!("    pub {}: {},", to_snake_case(parts[0].trim()), map_rust_type(parts[1].trim()))
                        } else {
                            format!("    pub {}: String,", to_snake_case(f.trim()))
                        }
                    })
                    .collect::<Vec<_>>()
                    .join("\n");
                format!(
                    "#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\npub struct {} {{\n{}\n}}",
                    to_pascal_case(&n.name),
                    if fields.is_empty() { "    // no fields".to_string() } else { fields }
                )
            })
            .collect();

        // Function stubs from non-type Function nodes
        let stubs: Vec<FunctionStub> = doc.function_nodes()
            .iter()
            .filter(|n| n.kind_prop().unwrap_or("function") != "type")
            .map(|n| {
                let placeholder = format!("// ORACLE_BODY_{}", n.id);
                FunctionStub {
                    node_id: n.id.clone(),
                    name: to_snake_case(&n.name),
                    signature: format!(
                        "pub fn {}() -> String",
                        to_snake_case(&n.name)
                    ),
                    body_placeholder: placeholder,
                }
            })
            .collect();

        files.push(ScaffoldFile {
            path: "src/lib.rs".to_string(),
            language: "rust".to_string(),
            imports,
            type_definitions: type_defs,
            function_stubs: stubs,
        });

        files
    }

    fn assemble(
        &self,
        scaffolds: &[ScaffoldFile],
        oracle_bodies: &BTreeMap<String, String>,
    ) -> Vec<EmittedFile> {
        let mut emitted = Vec::new();

        for scaffold in scaffolds {
            let mut content = String::new();

            // Header comment
            content.push_str("// Generated by isls-multilang RustBackend\n");
            content.push_str("// Scaffold: backend. Logic: Oracle.\n\n");

            // Imports
            if !scaffold.imports.is_empty() {
                for imp in &scaffold.imports {
                    content.push_str(imp);
                    content.push('\n');
                }
                content.push('\n');
            }

            // Type definitions
            for td in &scaffold.type_definitions {
                content.push_str(td);
                content.push_str("\n\n");
            }

            // Functions
            let scaffold_before = count_lines(&content);
            let mut oracle_lines = 0;

            for stub in &scaffold.function_stubs {
                content.push_str(&format!("{} {{\n", stub.signature));
                if let Some(body) = oracle_bodies.get(&stub.node_id) {
                    let body_trimmed = indent_body(body, 4);
                    oracle_lines += count_lines(&body_trimmed);
                    content.push_str(&body_trimmed);
                } else {
                    content.push_str(&format!("    {}\n", stub.body_placeholder));
                    content.push_str("    unimplemented!(\"Oracle body not provided\")\n");
                }
                content.push_str("}\n\n");
            }

            let total_lines = count_lines(&content);
            emitted.push(EmittedFile {
                path: scaffold.path.clone(),
                content,
                language: "rust".to_string(),
                scaffold_lines: scaffold_before + (total_lines - scaffold_before).saturating_sub(oracle_lines),
                oracle_lines,
            });
        }

        // Emit Cargo.toml
        let cargo_toml = format!(
            "[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\nserde = {{ version = \"1\", features = [\"derive\"] }}\nserde_json = \"1\"\n",
            "generated-crate"
        );
        emitted.push(EmittedFile {
            path: "Cargo.toml".to_string(),
            content: cargo_toml.clone(),
            language: "toml".to_string(),
            scaffold_lines: count_lines(&cargo_toml),
            oracle_lines: 0,
        });

        emitted
    }
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

fn to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 { out.push('_'); }
        out.push(ch.to_lowercase().next().unwrap_or(ch));
    }
    out.replace(['-', ' '], "_")
}

fn to_pascal_case(s: &str) -> String {
    s.split(['_', '-', ' '])
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn to_rust_module_name(s: &str) -> String {
    to_snake_case(s)
}

fn map_rust_type(t: &str) -> &str {
    match t.trim() {
        "i64" | "i32" | "i8" => t.trim(),
        "f64" | "f32" => t.trim(),
        "bool" => "bool",
        "String" | "string" | "str" => "String",
        _ => "String",
    }
}

fn indent_body(body: &str, spaces: usize) -> String {
    let indent = " ".repeat(spaces);
    body.lines()
        .map(|line| {
            if line.is_empty() { String::new() } else { format!("{}{}", indent, line) }
        })
        .collect::<Vec<_>>()
        .join("\n")
        + "\n"
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::glyph_ir::{IrDocument, IrNode, IrEdge, NodeKind, EdgeKind};

    fn make_doc() -> IrDocument {
        let mut doc = IrDocument::new("test", "test-id");
        let root = IrNode::new("n_root", NodeKind::Module, "root");
        let f1 = IrNode::new("n_fn_0", NodeKind::Function, "healthCheck");
        doc.nodes.push(root);
        doc.nodes.push(f1);
        doc.edges.push(IrEdge::new("n_root", "n_fn_0", EdgeKind::Contains));
        doc.canonicalize();
        doc
    }

    // AT-BB4: Generate scaffold; verify .rs files with correct pub fn signatures.
    #[test]
    fn at_bb4_rust_scaffold() {
        let backend = RustBackend;
        let doc = make_doc();
        let scaffolds = backend.scaffold(&doc);
        assert!(!scaffolds.is_empty(), "AT-BB4: must produce scaffold files");
        let lib = scaffolds.iter().find(|f| f.path == "src/lib.rs")
            .expect("AT-BB4: src/lib.rs must exist");
        assert!(!lib.function_stubs.is_empty(), "AT-BB4: must have function stubs");
        let stub = &lib.function_stubs[0];
        assert!(stub.signature.contains("pub fn"), "AT-BB4: signature must contain 'pub fn'");
    }

    // AT-BB9: Scaffold + mock Oracle bodies → complete files with both scaffold and body content.
    #[test]
    fn at_bb9_assembly() {
        let backend = RustBackend;
        let doc = make_doc();
        let scaffolds = backend.scaffold(&doc);
        let mut oracle_bodies = BTreeMap::new();
        oracle_bodies.insert("n_fn_0".to_string(), "format!(\"ok\")".to_string());
        let files = backend.assemble(&scaffolds, &oracle_bodies);
        assert!(!files.is_empty(), "AT-BB9: must emit files");
        let lib = files.iter().find(|f| f.path == "src/lib.rs").expect("AT-BB9: src/lib.rs");
        assert!(lib.content.contains("pub fn"), "AT-BB9: must have pub fn");
        assert!(lib.oracle_lines > 0, "AT-BB9: oracle_lines must be > 0");
    }

    // AT-BB8: Cross-language type — same field names in Rust scaffold.
    #[test]
    fn at_bb8_crosslang_types_rust() {
        use std::collections::BTreeMap as BM;
        use serde_json::json;
        let mut doc = IrDocument::new("test", "test-id");
        let root = IrNode::new("n_root", NodeKind::Module, "root");
        let mut type_node = IrNode::new("n_type_user", NodeKind::Function, "User");
        type_node.params = Some(vec!["id:i64".into(), "name:String".into(), "email:String".into()]);
        let mut props = BM::new();
        props.insert("kind".into(), json!("type"));
        type_node.properties = Some(props);
        doc.nodes.push(root);
        doc.nodes.push(type_node);
        doc.edges.push(IrEdge::new("n_root", "n_type_user", EdgeKind::Contains));
        doc.canonicalize();

        let backend = RustBackend;
        let scaffolds = backend.scaffold(&doc);
        let lib = scaffolds.iter().find(|f| f.path == "src/lib.rs").expect("lib.rs");
        assert!(lib.type_definitions.iter().any(|td| td.contains("pub struct User")),
            "AT-BB8: must contain pub struct User");
        assert!(lib.type_definitions.iter().any(|td| td.contains("pub id")),
            "AT-BB8: must contain field 'id'");
        assert!(lib.type_definitions.iter().any(|td| td.contains("pub name")),
            "AT-BB8: must contain field 'name'");
    }
}
