// isls-multilang/src/backends/sql_backend.rs
//
// SqlBackend: CREATE TABLE from type nodes, CREATE INDEX from edges,
//             migration numbering.

use std::collections::BTreeMap;
use crate::codegen::{CodegenBackend, EmittedFile, FunctionStub, ScaffoldFile, count_lines};
use crate::glyph_ir::IrDocument;

pub struct SqlBackend;

impl CodegenBackend for SqlBackend {
    fn language(&self) -> &str { "sql" }
    fn extension(&self) -> &str { "sql" }

    fn scaffold(&self, doc: &IrDocument) -> Vec<ScaffoldFile> {
        // Type definitions = CREATE TABLE statements
        let type_defs: Vec<String> = doc.function_nodes()
            .iter()
            .filter(|n| n.kind_prop().unwrap_or("function") == "type")
            .map(|n| {
                let table = to_snake_plural(&n.name);
                let cols: Vec<String> = n.params.as_deref().unwrap_or(&[])
                    .iter()
                    .enumerate()
                    .map(|(i, f)| {
                        let parts: Vec<&str> = f.splitn(2, ':').collect();
                        let col = parts[0].trim();
                        let sql_type = if parts.len() == 2 {
                            map_sql_type(parts[1].trim())
                        } else {
                            "TEXT"
                        };
                        let constraint = if i == 0 { " PRIMARY KEY" } else { " NOT NULL" };
                        format!("    {} {}{}", col, sql_type, constraint)
                    })
                    .collect();
                format!(
                    "CREATE TABLE {} (\n{}\n);",
                    table,
                    if cols.is_empty() { "    id BIGINT PRIMARY KEY".to_string() } else { cols.join(",\n") }
                )
            })
            .collect();

        // Indexes from CalleeRef edges
        let mut index_defs: Vec<String> = doc.callee_edges()
            .iter()
            .filter_map(|e| {
                let from = doc.nodes.iter().find(|n| n.id == e.from)?;
                let to = doc.nodes.iter().find(|n| n.id == e.to)?;
                if from.kind_prop().unwrap_or("") == "type" && to.kind_prop().unwrap_or("") == "type" {
                    Some(format!(
                        "CREATE INDEX idx_{}_on_{} ON {} (id);",
                        to_snake_plural(&from.name),
                        to_snake_plural(&to.name),
                        to_snake_plural(&from.name),
                    ))
                } else {
                    None
                }
            })
            .collect();
        index_defs.sort();
        index_defs.dedup();

        let mut all_sql = type_defs.clone();
        all_sql.extend(index_defs);

        // Function stubs for non-type nodes (stored procedures / queries)
        let stubs: Vec<FunctionStub> = doc.function_nodes()
            .iter()
            .filter(|n| n.kind_prop().unwrap_or("function") != "type")
            .map(|n| {
                let placeholder = format!("-- ORACLE_BODY_{}", n.id);
                FunctionStub {
                    node_id: n.id.clone(),
                    name: to_snake_case(&n.name),
                    signature: format!("-- Query: {}", n.name),
                    body_placeholder: placeholder,
                }
            })
            .collect();

        vec![ScaffoldFile {
            path: "migrations/0001_initial.sql".to_string(),
            language: "sql".to_string(),
            imports: vec![],
            type_definitions: all_sql,
            function_stubs: stubs,
        }]
    }

    fn assemble(
        &self,
        scaffolds: &[ScaffoldFile],
        oracle_bodies: &BTreeMap<String, String>,
    ) -> Vec<EmittedFile> {
        let mut emitted = Vec::new();

        for scaffold in scaffolds {
            let mut content = String::new();
            content.push_str("-- Generated by isls-multilang SqlBackend\n\n");

            for td in &scaffold.type_definitions {
                content.push_str(td);
                content.push_str("\n\n");
            }

            let scaffold_base = count_lines(&content);
            let mut oracle_lines = 0;

            for stub in &scaffold.function_stubs {
                content.push_str(&format!("{}\n", stub.signature));
                if let Some(body) = oracle_bodies.get(&stub.node_id) {
                    oracle_lines += count_lines(body);
                    content.push_str(body);
                    content.push('\n');
                } else {
                    content.push_str(&format!("{}\n", stub.body_placeholder));
                }
                content.push('\n');
            }

            emitted.push(EmittedFile {
                path: scaffold.path.clone(),
                content: content.clone(),
                language: "sql".to_string(),
                scaffold_lines: scaffold_base,
                oracle_lines,
            });
        }

        emitted
    }
}

fn to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 { out.push('_'); }
        out.push(ch.to_lowercase().next().unwrap_or(ch));
    }
    out.replace('-', "_").replace(' ', "_")
}

fn to_snake_plural(s: &str) -> String {
    let base = to_snake_case(s);
    if base.ends_with('s') { base } else { base + "s" }
}

fn map_sql_type(t: &str) -> &str {
    match t.trim() {
        "i64" | "i32" => "BIGINT",
        "i8" => "SMALLINT",
        "f64" | "f32" => "DOUBLE PRECISION",
        "bool" => "BOOLEAN",
        "String" | "string" | "str" => "TEXT",
        _ => "TEXT",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::glyph_ir::{IrDocument, IrNode, IrEdge, NodeKind, EdgeKind};
    use std::collections::BTreeMap as BM;
    use serde_json::json;

    // AT-BB7: verify .sql files with correct CREATE TABLE.
    #[test]
    fn at_bb7_sql_scaffold() {
        let mut doc = IrDocument::new("test", "test-id");
        let root = IrNode::new("n_root", NodeKind::Module, "root");
        let mut type_node = IrNode::new("n_type_user", NodeKind::Function, "User");
        type_node.params = Some(vec!["id:i64".into(), "name:String".into(), "email:String".into()]);
        let mut props = BM::new();
        props.insert("kind".into(), json!("type"));
        type_node.properties = Some(props);
        doc.nodes.push(root);
        doc.nodes.push(type_node);
        doc.edges.push(IrEdge::new("n_root", "n_type_user", EdgeKind::Contains));
        doc.canonicalize();

        let backend = SqlBackend;
        let scaffolds = backend.scaffold(&doc);
        assert!(!scaffolds.is_empty(), "AT-BB7: must have scaffold files");
        let migration = &scaffolds[0];
        assert!(migration.type_definitions.iter().any(|td| td.contains("CREATE TABLE")),
            "AT-BB7: must have CREATE TABLE");
        assert!(migration.type_definitions.iter().any(|td| td.contains("users")),
            "AT-BB7: must have 'users' table");
    }
}
