// isls-multilang/src/backends/typescript_backend.rs
//
// TypeScriptBackend: export interface for types, export function signatures,
//                   import from IR edges, package.json.

use std::collections::BTreeMap;
use crate::codegen::{CodegenBackend, EmittedFile, FunctionStub, ScaffoldFile, count_lines};
use crate::glyph_ir::IrDocument;

pub struct TypeScriptBackend;

impl CodegenBackend for TypeScriptBackend {
    fn language(&self) -> &str { "typescript" }
    fn extension(&self) -> &str { "ts" }

    fn scaffold(&self, doc: &IrDocument) -> Vec<ScaffoldFile> {
        // Imports from CalleeRef edges
        let imports: Vec<String> = doc.callee_edges()
            .iter()
            .filter_map(|e| {
                let to_node = doc.nodes.iter().find(|n| n.id == e.to)?;
                Some(format!("import {{ {} }} from './{}.js';", to_pascal_case(&to_node.name), to_kebab_case(&to_node.name)))
            })
            .collect::<std::collections::HashSet<_>>()
            .into_iter()
            .collect();

        // Type definitions (interfaces) from kind_prop == "type"
        let type_defs: Vec<String> = doc.function_nodes()
            .iter()
            .filter(|n| n.kind_prop().unwrap_or("function") == "type")
            .map(|n| {
                let fields = n.params.as_deref().unwrap_or(&[])
                    .iter()
                    .map(|f| {
                        let parts: Vec<&str> = f.splitn(2, ':').collect();
                        if parts.len() == 2 {
                            format!("  {}: {};", parts[0].trim(), map_ts_type(parts[1].trim()))
                        } else {
                            format!("  {}: string;", f.trim())
                        }
                    })
                    .collect::<Vec<_>>()
                    .join("\n");
                format!(
                    "export interface {} {{\n{}\n}}",
                    to_pascal_case(&n.name),
                    if fields.is_empty() { "  // no fields".to_string() } else { fields }
                )
            })
            .collect();

        // Function stubs
        let stubs: Vec<FunctionStub> = doc.function_nodes()
            .iter()
            .filter(|n| n.kind_prop().unwrap_or("function") != "type")
            .map(|n| {
                let placeholder = format!("// ORACLE_BODY_{}", n.id);
                FunctionStub {
                    node_id: n.id.clone(),
                    name: to_camel_case(&n.name),
                    signature: format!("export function {}(): string", to_camel_case(&n.name)),
                    body_placeholder: placeholder,
                }
            })
            .collect();

        vec![ScaffoldFile {
            path: "src/index.ts".to_string(),
            language: "typescript".to_string(),
            imports,
            type_definitions: type_defs,
            function_stubs: stubs,
        }]
    }

    fn assemble(
        &self,
        scaffolds: &[ScaffoldFile],
        oracle_bodies: &BTreeMap<String, String>,
    ) -> Vec<EmittedFile> {
        let mut emitted = Vec::new();

        for scaffold in scaffolds {
            let mut content = String::new();
            content.push_str("// Generated by isls-multilang TypeScriptBackend\n\n");

            for imp in &scaffold.imports {
                content.push_str(imp);
                content.push('\n');
            }
            if !scaffold.imports.is_empty() { content.push('\n'); }

            for td in &scaffold.type_definitions {
                content.push_str(td);
                content.push_str("\n\n");
            }

            let scaffold_base = count_lines(&content);
            let mut oracle_lines = 0;

            for stub in &scaffold.function_stubs {
                content.push_str(&format!("{} {{\n", stub.signature));
                if let Some(body) = oracle_bodies.get(&stub.node_id) {
                    let indented = indent_body(body, 2);
                    oracle_lines += count_lines(&indented);
                    content.push_str(&indented);
                } else {
                    content.push_str(&format!("  {}\n", stub.body_placeholder));
                    content.push_str("  throw new Error('Oracle body not provided');\n");
                }
                content.push_str("}\n\n");
            }

            emitted.push(EmittedFile {
                path: scaffold.path.clone(),
                content: content.clone(),
                language: "typescript".to_string(),
                scaffold_lines: scaffold_base + count_lines(&content).saturating_sub(scaffold_base + oracle_lines),
                oracle_lines,
            });
        }

        // package.json
        let pkg = r#"{
  "name": "generated-package",
  "version": "0.1.0",
  "scripts": { "build": "tsc", "test": "jest" },
  "devDependencies": { "typescript": "^5.0.0" }
}
"#;
        emitted.push(EmittedFile {
            path: "package.json".to_string(),
            content: pkg.to_string(),
            language: "json".to_string(),
            scaffold_lines: count_lines(pkg),
            oracle_lines: 0,
        });

        emitted
    }
}

fn to_pascal_case(s: &str) -> String {
    s.split(|c: char| c == '_' || c == '-' || c == ' ')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn to_camel_case(s: &str) -> String {
    let pascal = to_pascal_case(s);
    let mut chars = pascal.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_lowercase().collect::<String>() + chars.as_str(),
    }
}

fn to_kebab_case(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 { out.push('-'); }
        out.push(ch.to_lowercase().next().unwrap_or(ch));
    }
    out.replace('_', "-").replace(' ', "-")
}

fn map_ts_type(t: &str) -> &str {
    match t.trim() {
        "i64" | "i32" | "i8" | "f64" | "f32" | "usize" => "number",
        "bool" => "boolean",
        "String" | "string" | "str" => "string",
        _ => "string",
    }
}

fn indent_body(body: &str, spaces: usize) -> String {
    let indent = " ".repeat(spaces);
    body.lines()
        .map(|line| if line.is_empty() { String::new() } else { format!("{}{}", indent, line) })
        .collect::<Vec<_>>()
        .join("\n")
        + "\n"
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::glyph_ir::{IrDocument, IrNode, IrEdge, NodeKind, EdgeKind};
    use std::collections::BTreeMap as BM;
    use serde_json::json;

    fn make_doc_with_type() -> IrDocument {
        let mut doc = IrDocument::new("test", "test-id");
        let root = IrNode::new("n_root", NodeKind::Module, "root");
        let mut type_node = IrNode::new("n_type_user", NodeKind::Function, "User");
        type_node.params = Some(vec!["id:i64".into(), "name:String".into(), "email:String".into()]);
        let mut props = BM::new();
        props.insert("kind".into(), json!("type"));
        type_node.properties = Some(props);
        doc.nodes.push(root);
        doc.nodes.push(type_node);
        doc.edges.push(IrEdge::new("n_root", "n_type_user", EdgeKind::Contains));
        doc.canonicalize();
        doc
    }

    // AT-BB5: verify .ts files with correct export interface definitions.
    #[test]
    fn at_bb5_ts_scaffold() {
        let backend = TypeScriptBackend;
        let mut doc = IrDocument::new("test", "test-id");
        let root = IrNode::new("n_root", NodeKind::Module, "root");
        let f1 = IrNode::new("n_fn_0", NodeKind::Function, "getHealth");
        doc.nodes.push(root);
        doc.nodes.push(f1);
        doc.edges.push(IrEdge::new("n_root", "n_fn_0", EdgeKind::Contains));
        doc.canonicalize();

        let scaffolds = backend.scaffold(&doc);
        assert!(!scaffolds.is_empty(), "AT-BB5: must have scaffold files");
        let f = &scaffolds[0];
        assert!(!f.function_stubs.is_empty(), "AT-BB5: must have function stubs");
        let stub = &f.function_stubs[0];
        assert!(stub.signature.contains("export function"), "AT-BB5: must have export function");
    }

    // AT-BB8: Cross-language type — same field names in TypeScript.
    #[test]
    fn at_bb8_crosslang_types_ts() {
        let backend = TypeScriptBackend;
        let doc = make_doc_with_type();
        let scaffolds = backend.scaffold(&doc);
        let idx = scaffolds.iter().find(|f| f.path.contains("index.ts")).expect("index.ts");
        assert!(idx.type_definitions.iter().any(|td| td.contains("export interface User")),
            "AT-BB8: must contain 'export interface User'");
        assert!(idx.type_definitions.iter().any(|td| td.contains("id:")),
            "AT-BB8: must contain field 'id'");
        assert!(idx.type_definitions.iter().any(|td| td.contains("name:")),
            "AT-BB8: must contain field 'name'");
    }
}
