// Copyright (c) 2026 Sebastian Klemm
// SPDX-License-Identifier: MIT
//! Tera template registry for full-stack code generation.
//!
//! All templates are embedded as string constants and registered into a
//! shared `Tera` engine at startup.

use tera::Tera;

/// Build the shared Tera template engine with all code generation templates.
pub fn build_engine() -> Result<Tera, tera::Error> {
    let mut tera = Tera::default();

    tera.add_raw_template("backend_cargo_toml", BACKEND_CARGO_TOML)?;
    tera.add_raw_template("main_rs", MAIN_RS)?;
    tera.add_raw_template("config_rs", CONFIG_RS)?;
    tera.add_raw_template("model_rs", MODEL_RS)?;
    tera.add_raw_template("migration_sql", MIGRATION_SQL)?;
    tera.add_raw_template("queries_rs", QUERIES_RS)?;
    tera.add_raw_template("pool_rs", POOL_RS)?;
    tera.add_raw_template("service_rs", SERVICE_RS)?;
    tera.add_raw_template("api_rs", API_RS)?;
    tera.add_raw_template("index_html", INDEX_HTML)?;
    tera.add_raw_template("app_js", APP_JS)?;
    tera.add_raw_template("page_js", PAGE_JS)?;
    tera.add_raw_template("client_js", CLIENT_JS)?;
    tera.add_raw_template("style_css", STYLE_CSS)?;
    tera.add_raw_template("integration_test_rs", INTEGRATION_TEST_RS)?;
    tera.add_raw_template("docker_compose", DOCKER_COMPOSE)?;
    tera.add_raw_template("dockerfile_backend", DOCKERFILE_BACKEND)?;
    tera.add_raw_template("env_example", ENV_EXAMPLE)?;
    tera.add_raw_template("gitignore", GITIGNORE)?;
    tera.add_raw_template("readme_md", README_MD)?;

    Ok(tera)
}

// ─── Rust Backend Templates ───────────────────────────────────────────────────

const BACKEND_CARGO_TOML: &str = r#"[package]
name = "{{ app_name }}"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-rt = "2"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-native-tls", "chrono", "uuid"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = "0.3"
jsonwebtoken = "9"
bcrypt = "0.15"

[dev-dependencies]
actix-web = { version = "4", features = ["macros"] }
"#;

const MAIN_RS: &str = r#"// {{ app_name }} — Generated by ISLS Full-Stack Autonomy
// Copyright (c) 2026 Sebastian Klemm — MIT License

use actix_web::{middleware, web, App, HttpServer};
use dotenv::dotenv;
use std::env;

mod config;
mod models;
mod database;
mod services;
mod api;
mod errors;

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    dotenv().ok();
    tracing_subscriber::fmt::init();

    let config = config::AppConfig::from_env().expect("Failed to load config");
    let pool = database::pool::create_pool(&config.database_url)
        .await
        .expect("Failed to create database pool");

    database::pool::run_migrations(&pool).await.expect("Failed to run migrations");

    let port = config.port;
    tracing::info!("Starting {{ app_name }} on port {}", port);

    HttpServer::new(move || {
        let cors = actix_cors::Cors::default()
            .allow_any_origin()
            .allow_any_method()
            .allow_any_header();

        App::new()
            .wrap(middleware::Logger::default())
            .wrap(cors)
            .app_data(web::Data::new(pool.clone()))
            .app_data(web::Data::new(config.clone()))
            .configure(api::configure_routes)
    })
    .bind(("0.0.0.0", port))?
    .run()
    .await
}
"#;

const CONFIG_RS: &str = r#"// Configuration — {{ app_name }}

use std::env;

#[derive(Clone, Debug)]
pub struct AppConfig {
    pub database_url: String,
    pub port: u16,
    pub jwt_secret: String,
}

impl AppConfig {
    pub fn from_env() -> Result<Self, String> {
        Ok(Self {
            database_url: env::var("DATABASE_URL")
                .unwrap_or_else(|_| "postgres://postgres:postgres@localhost/{{ app_name | replace(from="-", to="_") }}".to_string()),
            port: env::var("PORT")
                .ok()
                .and_then(|p| p.parse().ok())
                .unwrap_or(8080),
            jwt_secret: env::var("JWT_SECRET")
                .unwrap_or_else(|_| "change-me-in-production".to_string()),
        })
    }
}
"#;

const MODEL_RS: &str = r#"// Model: {{ entity }} — generated by ISLS
use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

/// {{ entity }} entity.
#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct {{ entity }} {
    pub id: i64,
    pub name: String,
    pub description: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Payload for creating a new {{ entity }}.
#[derive(Debug, Clone, Deserialize)]
pub struct Create{{ entity }} {
    pub name: String,
    pub description: Option<String>,
}

/// Payload for updating an existing {{ entity }}.
#[derive(Debug, Clone, Deserialize)]
pub struct Update{{ entity }} {
    pub name: Option<String>,
    pub description: Option<String>,
}

impl {{ entity }} {
    /// Validate the entity fields.
    pub fn validate(name: &str) -> Result<(), String> {
        if name.trim().is_empty() {
            return Err("name must not be empty".to_string());
        }
        if name.len() > 255 {
            return Err("name must be at most 255 characters".to_string());
        }
        Ok(())
    }
}
"#;

const MIGRATION_SQL: &str = r#"-- Migration: {{ app_name }} initial schema
-- Generated by ISLS Full-Stack Autonomy

{% for entity in entities %}
CREATE TABLE IF NOT EXISTS {{ entity | lower }}s (
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_{{ entity | lower }}s_name ON {{ entity | lower }}s(name);

{% endfor %}
"#;

const QUERIES_RS: &str = r#"// Database queries: {{ module }} — generated by ISLS
use sqlx::PgPool;
use crate::models::*;

{% for entity in entities %}
/// List all {{ entity }}s.
pub async fn list_{{ entity | lower }}s(pool: &PgPool) -> Result<Vec<{{ entity }}>, sqlx::Error> {
    sqlx::query_as!(
        {{ entity }},
        "SELECT id, name, description, created_at, updated_at FROM {{ entity | lower }}s ORDER BY id"
    )
    .fetch_all(pool)
    .await
}

/// Get a {{ entity }} by id.
pub async fn get_{{ entity | lower }}(pool: &PgPool, id: i64) -> Result<Option<{{ entity }}>, sqlx::Error> {
    sqlx::query_as!(
        {{ entity }},
        "SELECT id, name, description, created_at, updated_at FROM {{ entity | lower }}s WHERE id = $1",
        id
    )
    .fetch_optional(pool)
    .await
}

/// Create a new {{ entity }}.
pub async fn create_{{ entity | lower }}(pool: &PgPool, payload: &Create{{ entity }}) -> Result<{{ entity }}, sqlx::Error> {
    sqlx::query_as!(
        {{ entity }},
        "INSERT INTO {{ entity | lower }}s (name, description, created_at, updated_at)
         VALUES ($1, $2, NOW(), NOW())
         RETURNING id, name, description, created_at, updated_at",
        payload.name,
        payload.description,
    )
    .fetch_one(pool)
    .await
}

/// Update a {{ entity }}.
pub async fn update_{{ entity | lower }}(pool: &PgPool, id: i64, payload: &Update{{ entity }}) -> Result<Option<{{ entity }}>, sqlx::Error> {
    sqlx::query_as!(
        {{ entity }},
        "UPDATE {{ entity | lower }}s
         SET name = COALESCE($1, name),
             description = COALESCE($2, description),
             updated_at = NOW()
         WHERE id = $3
         RETURNING id, name, description, created_at, updated_at",
        payload.name,
        payload.description,
        id,
    )
    .fetch_optional(pool)
    .await
}

/// Delete a {{ entity }}.
pub async fn delete_{{ entity | lower }}(pool: &PgPool, id: i64) -> Result<bool, sqlx::Error> {
    let result = sqlx::query!(
        "DELETE FROM {{ entity | lower }}s WHERE id = $1",
        id
    )
    .execute(pool)
    .await?;
    Ok(result.rows_affected() > 0)
}

{% endfor %}
"#;

const POOL_RS: &str = r#"// Database pool — generated by ISLS
use sqlx::{PgPool, postgres::PgPoolOptions};

/// Create a connection pool from the given database URL.
pub async fn create_pool(database_url: &str) -> Result<PgPool, sqlx::Error> {
    PgPoolOptions::new()
        .max_connections(10)
        .connect(database_url)
        .await
}

/// Run embedded SQL migrations.
pub async fn run_migrations(pool: &PgPool) -> Result<(), sqlx::Error> {
    sqlx::migrate!("./migrations").run(pool).await.map_err(|e| {
        sqlx::Error::Configuration(e.to_string().into())
    })
}
"#;

const SERVICE_RS: &str = r#"// Service: {{ module }} — generated by ISLS
use sqlx::PgPool;
use crate::models::*;
use crate::database::{{ module }}_queries as queries;

{% for entity in entities %}
/// List all {{ entity }}s.
pub async fn list_{{ entity | lower }}s(pool: &PgPool) -> Result<Vec<{{ entity }}>, String> {
    queries::list_{{ entity | lower }}s(pool).await.map_err(|e| e.to_string())
}

/// Get a single {{ entity }} by id.
pub async fn get_{{ entity | lower }}(pool: &PgPool, id: i64) -> Result<Option<{{ entity }}>, String> {
    queries::get_{{ entity | lower }}(pool, id).await.map_err(|e| e.to_string())
}

/// Create a new {{ entity }}.
pub async fn create_{{ entity | lower }}(pool: &PgPool, payload: Create{{ entity }}) -> Result<{{ entity }}, String> {
    {{ entity }}::validate(&payload.name)?;
    queries::create_{{ entity | lower }}(pool, &payload).await.map_err(|e| e.to_string())
}

/// Update an existing {{ entity }}.
pub async fn update_{{ entity | lower }}(pool: &PgPool, id: i64, payload: Update{{ entity }}) -> Result<Option<{{ entity }}>, String> {
    if let Some(name) = &payload.name {
        {{ entity }}::validate(name)?;
    }
    queries::update_{{ entity | lower }}(pool, id, &payload).await.map_err(|e| e.to_string())
}

/// Delete a {{ entity }}.
pub async fn delete_{{ entity | lower }}(pool: &PgPool, id: i64) -> Result<bool, String> {
    queries::delete_{{ entity | lower }}(pool, id).await.map_err(|e| e.to_string())
}

{% endfor %}
"#;

const API_RS: &str = r#"// API handlers: {{ module }} — generated by ISLS
use actix_web::{web, HttpResponse, Responder};
use sqlx::PgPool;
use crate::models::*;
use crate::services::{{ module }} as svc;

{% for entity in entities %}
/// GET /api/{{ entity | lower }}s — list all {{ entity }}s
pub async fn list_{{ entity | lower }}s(pool: web::Data<PgPool>) -> impl Responder {
    match svc::list_{{ entity | lower }}s(&pool).await {
        Ok(items) => HttpResponse::Ok().json(items),
        Err(e) => HttpResponse::InternalServerError().json(serde_json::json!({"error": e})),
    }
}

/// GET /api/{{ entity | lower }}s/{id} — get a {{ entity }}
pub async fn get_{{ entity | lower }}(
    pool: web::Data<PgPool>,
    path: web::Path<i64>,
) -> impl Responder {
    let id = path.into_inner();
    match svc::get_{{ entity | lower }}(&pool, id).await {
        Ok(Some(item)) => HttpResponse::Ok().json(item),
        Ok(None) => HttpResponse::NotFound().json(serde_json::json!({"error": "not found"})),
        Err(e) => HttpResponse::InternalServerError().json(serde_json::json!({"error": e})),
    }
}

/// POST /api/{{ entity | lower }}s — create a {{ entity }}
pub async fn create_{{ entity | lower }}(
    pool: web::Data<PgPool>,
    body: web::Json<Create{{ entity }}>,
) -> impl Responder {
    match svc::create_{{ entity | lower }}(&pool, body.into_inner()).await {
        Ok(item) => HttpResponse::Created().json(item),
        Err(e) => HttpResponse::BadRequest().json(serde_json::json!({"error": e})),
    }
}

/// PUT /api/{{ entity | lower }}s/{id} — update a {{ entity }}
pub async fn update_{{ entity | lower }}(
    pool: web::Data<PgPool>,
    path: web::Path<i64>,
    body: web::Json<Update{{ entity }}>,
) -> impl Responder {
    let id = path.into_inner();
    match svc::update_{{ entity | lower }}(&pool, id, body.into_inner()).await {
        Ok(Some(item)) => HttpResponse::Ok().json(item),
        Ok(None) => HttpResponse::NotFound().json(serde_json::json!({"error": "not found"})),
        Err(e) => HttpResponse::BadRequest().json(serde_json::json!({"error": e})),
    }
}

/// DELETE /api/{{ entity | lower }}s/{id} — delete a {{ entity }}
pub async fn delete_{{ entity | lower }}(
    pool: web::Data<PgPool>,
    path: web::Path<i64>,
) -> impl Responder {
    let id = path.into_inner();
    match svc::delete_{{ entity | lower }}(&pool, id).await {
        Ok(true) => HttpResponse::NoContent().finish(),
        Ok(false) => HttpResponse::NotFound().json(serde_json::json!({"error": "not found"})),
        Err(e) => HttpResponse::InternalServerError().json(serde_json::json!({"error": e})),
    }
}

{% endfor %}

/// Register all {{ module }} routes.
pub fn configure(cfg: &mut web::ServiceConfig) {
    {% for entity in entities %}
    cfg.service(
        web::scope("/api/{{ entity | lower }}s")
            .route("", web::get().to(list_{{ entity | lower }}s))
            .route("", web::post().to(create_{{ entity | lower }}))
            .route("/{id}", web::get().to(get_{{ entity | lower }}))
            .route("/{id}", web::put().to(update_{{ entity | lower }}))
            .route("/{id}", web::delete().to(delete_{{ entity | lower }}))
    );
    {% endfor %}
}
"#;

// ─── Frontend Templates ───────────────────────────────────────────────────────

const INDEX_HTML: &str = r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{ app_name }}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <nav class="navbar">
    <a href="/" class="nav-brand">{{ app_name }}</a>
    <ul class="nav-links">
      <li><a href="/" data-route="/">Dashboard</a></li>
      {% for module in modules %}
      <li><a href="/{{ module }}" data-route="/{{ module }}">{{ module | title }}</a></li>
      {% endfor %}
    </ul>
  </nav>
  <main id="app">Loading...</main>
  <script type="module" src="src/app.js"></script>
</body>
</html>
"#;

const APP_JS: &str = r#"// {{ app_name }} — SPA Router — generated by ISLS
import { API_BASE } from './api/client.js';

{% for module in modules %}
import { render as render_{{ module }} } from './pages/{{ module }}.js';
{% endfor %}
import { render as renderDashboard } from './pages/dashboard.js';

const routes = {
  '/': renderDashboard,
  {% for module in modules %}
  '/{{ module }}': render_{{ module }},
  {% endfor %}
};

function navigate(path) {
  const render = routes[path] || renderDashboard;
  document.getElementById('app').innerHTML = '';
  render(document.getElementById('app'));
  document.querySelectorAll('[data-route]').forEach(el => {
    el.classList.toggle('active', el.dataset.route === path);
  });
}

document.querySelectorAll('[data-route]').forEach(el => {
  el.addEventListener('click', e => {
    e.preventDefault();
    const path = el.dataset.route;
    window.history.pushState({}, '', path);
    navigate(path);
  });
});

window.addEventListener('popstate', () => navigate(window.location.pathname));
navigate(window.location.pathname);
"#;

const PAGE_JS: &str = r#"// Page: {{ module }} — generated by ISLS
import { apiFetch } from '../api/client.js';

export async function render(container) {
  container.innerHTML = `
    <div class="page">
      <h1>{{ module | title }}</h1>
      <div class="toolbar">
        <button id="btn-create-{{ module }}">+ New</button>
      </div>
      <div id="{{ module }}-list" class="data-table-wrapper">Loading...</div>
      <div id="{{ module }}-form" class="form-panel" style="display:none"></div>
    </div>
  `;

  await loadList();

  document.getElementById('btn-create-{{ module }}').addEventListener('click', () => showForm());

  async function loadList() {
    const items = await apiFetch('/api/{{ primary_entity | lower }}s');
    const wrapper = document.getElementById('{{ module }}-list');
    if (!items || items.length === 0) {
      wrapper.innerHTML = '<p class="empty-state">No items found.</p>';
      return;
    }
    wrapper.innerHTML = `
      <table class="data-table">
        <thead><tr>
          <th>ID</th><th>Name</th><th>Description</th><th>Actions</th>
        </tr></thead>
        <tbody>${items.map(item => `
          <tr>
            <td>${item.id}</td>
            <td>${item.name || ''}</td>
            <td>${item.description || ''}</td>
            <td>
              <button onclick="editItem(${item.id})">Edit</button>
              <button onclick="deleteItem(${item.id})">Delete</button>
            </td>
          </tr>`).join('')}
        </tbody>
      </table>`;
  }

  function showForm(item = null) {
    const panel = document.getElementById('{{ module }}-form');
    panel.style.display = 'block';
    panel.innerHTML = `
      <form id="entity-form">
        <h2>${item ? 'Edit' : 'New'} {{ primary_entity }}</h2>
        <label>Name<input name="name" value="${item?.name || ''}" required /></label>
        <label>Description<textarea name="description">${item?.description || ''}</textarea></label>
        <div class="form-actions">
          <button type="submit">${item ? 'Update' : 'Create'}</button>
          <button type="button" id="cancel-form">Cancel</button>
        </div>
      </form>`;
    document.getElementById('cancel-form').addEventListener('click', () => { panel.style.display = 'none'; });
    document.getElementById('entity-form').addEventListener('submit', async e => {
      e.preventDefault();
      const data = Object.fromEntries(new FormData(e.target));
      if (item) {
        await apiFetch(`/api/{{ primary_entity | lower }}s/${item.id}`, { method: 'PUT', body: JSON.stringify(data) });
      } else {
        await apiFetch('/api/{{ primary_entity | lower }}s', { method: 'POST', body: JSON.stringify(data) });
      }
      panel.style.display = 'none';
      await loadList();
    });
  }

  window.editItem = async (id) => {
    const item = await apiFetch(`/api/{{ primary_entity | lower }}s/${id}`);
    showForm(item);
  };

  window.deleteItem = async (id) => {
    if (!confirm('Delete this item?')) return;
    await apiFetch(`/api/{{ primary_entity | lower }}s/${id}`, { method: 'DELETE' });
    await loadList();
  };
}
"#;

const CLIENT_JS: &str = r#"// API Client — generated by ISLS
export const API_BASE = 'http://localhost:8080';

export async function apiFetch(path, options = {}) {
  const token = localStorage.getItem('jwt_token');
  const headers = {
    'Content-Type': 'application/json',
    ...(token ? { 'Authorization': `Bearer ${token}` } : {}),
    ...(options.headers || {}),
  };
  try {
    const response = await fetch(`${API_BASE}${path}`, { ...options, headers });
    if (response.status === 204) return null;
    if (!response.ok) {
      const err = await response.json().catch(() => ({ error: response.statusText }));
      throw new Error(err.error || `HTTP ${response.status}`);
    }
    return response.json();
  } catch (e) {
    console.error(`API error for ${path}:`, e);
    throw e;
  }
}
"#;

const STYLE_CSS: &str = r#"/* {{ app_name }} — Minimal CSS — generated by ISLS */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  background: #f5f5f5;
  color: #333;
  line-height: 1.5;
}

.navbar {
  background: #1a1a2e;
  color: white;
  padding: 0.75rem 1.5rem;
  display: flex;
  align-items: center;
  gap: 2rem;
}

.nav-brand { color: white; text-decoration: none; font-weight: 700; font-size: 1.1rem; }
.nav-links { list-style: none; display: flex; gap: 1rem; }
.nav-links a { color: rgba(255,255,255,0.8); text-decoration: none; padding: 0.25rem 0.5rem; border-radius: 4px; }
.nav-links a:hover, .nav-links a.active { background: rgba(255,255,255,0.1); color: white; }

main { padding: 1.5rem; max-width: 1200px; margin: 0 auto; }

.page h1 { margin-bottom: 1rem; font-size: 1.5rem; }
.toolbar { margin-bottom: 1rem; }
button { padding: 0.4rem 0.9rem; border: none; border-radius: 4px; cursor: pointer; background: #1a1a2e; color: white; font-size: 0.9rem; }
button:hover { opacity: 0.85; }

.data-table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
.data-table th, .data-table td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid #eee; }
.data-table th { background: #f8f8f8; font-weight: 600; font-size: 0.875rem; }
.data-table td button { margin-right: 0.5rem; padding: 0.25rem 0.5rem; font-size: 0.8rem; }

.form-panel { background: white; border-radius: 8px; padding: 1.5rem; margin-top: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); max-width: 500px; }
.form-panel h2 { margin-bottom: 1rem; }
label { display: block; margin-bottom: 0.75rem; font-size: 0.9rem; }
label input, label textarea, label select { display: block; width: 100%; margin-top: 0.25rem; padding: 0.5rem; border: 1px solid #ddd; border-radius: 4px; font-size: 0.9rem; }
.form-actions { margin-top: 1rem; display: flex; gap: 0.5rem; }

.empty-state { color: #888; font-style: italic; padding: 1rem 0; }
"#;

// ─── Test Template ─────────────────────────────────────────────────────────────

const INTEGRATION_TEST_RS: &str = r#"// Integration tests: {{ module }} — generated by ISLS
use actix_web::{test, web, App};
use sqlx::PgPool;

// NOTE: These tests require a running PostgreSQL database.
// Set DATABASE_URL env var before running.

{% for entity in entities %}
#[actix_web::test]
async fn test_{{ entity | lower }}_crud() {
    // Setup: this test requires a database connection
    // Run with: DATABASE_URL=postgres://... cargo test
    let database_url = std::env::var("DATABASE_URL")
        .unwrap_or_else(|_| "postgres://postgres:postgres@localhost/{{ app_name | replace(from="-", to="_") }}_test".to_string());

    if let Ok(pool) = sqlx::PgPool::connect(&database_url).await {
        // Create
        let app = test::init_service(
            App::new()
                .app_data(web::Data::new(pool.clone()))
                .configure(crate::api::configure_routes)
        ).await;

        let req = test::TestRequest::post()
            .uri("/api/{{ entity | lower }}s")
            .set_json(serde_json::json!({
                "name": "Test {{ entity }}",
                "description": "Integration test item"
            }))
            .to_request();
        let resp = test::call_service(&app, req).await;
        assert!(resp.status().is_success(), "Create {{ entity }} should succeed");
    } else {
        // Skip if no database available
        eprintln!("Skipping {{ entity }} integration test — no database connection");
    }
}

{% endfor %}
"#;

// ─── Deployment Templates ─────────────────────────────────────────────────────

const DOCKER_COMPOSE: &str = r#"version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: {{ app_name | replace(from="-", to="_") }}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:${DB_PASSWORD:-postgres}@db/{{ app_name | replace(from="-", to="_") }}
      PORT: 8080
      JWT_SECRET: ${JWT_SECRET:-change-in-production}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

volumes:
  pgdata:
"#;

const DOCKERFILE_BACKEND: &str = r#"FROM rust:1.80-slim AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo 'fn main() {}' > src/main.rs
RUN cargo build --release && rm -rf src
COPY src ./src
RUN touch src/main.rs && cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates libssl3 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/{{ app_name }} /usr/local/bin/app
EXPOSE 8080
CMD ["app"]
"#;

const ENV_EXAMPLE: &str = r#"# {{ app_name }} environment configuration
DATABASE_URL=postgres://postgres:postgres@localhost/{{ app_name | replace(from="-", to="_") }}
PORT=8080
JWT_SECRET=change-me-to-a-secure-random-string
DB_PASSWORD=postgres
"#;

const GITIGNORE: &str = r#"/target/
.env
*.pdb
"#;

const README_MD: &str = r#"# {{ app_name }}

Generated by [ISLS Full-Stack Autonomy](https://github.com/LashSesh/graphity).

## Quick Start

### With Docker Compose

```bash
cp .env.example .env
# Edit .env and set a secure DB_PASSWORD and JWT_SECRET
docker-compose up -d
```

The backend API will be available at http://localhost:8080.
The frontend will be available at http://localhost:3000.

### Without Docker

**Requirements:** Rust 1.80+, PostgreSQL 14+

```bash
# Set up environment
cp .env.example .env
# Edit .env with your database URL

# Run migrations and start the backend
cd backend
cargo run

# Serve the frontend
cd ../frontend
python3 -m http.server 3000
```

## API Endpoints

{% for module in modules %}
### {{ module | title }}

{% for entity in modules %}
- `GET /api/{{ entity | lower }}s` — List all
- `POST /api/{{ entity | lower }}s` — Create
- `GET /api/{{ entity | lower }}s/{id}` — Get by ID
- `PUT /api/{{ entity | lower }}s/{id}` — Update
- `DELETE /api/{{ entity | lower }}s/{id}` — Delete
{% endfor %}

{% endfor %}

## Evidence Chain

The `evidence/` directory contains cryptographic proof of the generation process:

- `generation_manifest.json` — what was generated, in what order
- `crystal_registry.json` — all blueprints produced
- `constraint_proof.json` — SHA-256 chain verifying constraints were met

---
*Generated by ISLS Full-Stack Autonomy — © 2026 Sebastian Klemm — MIT License*
"#;
