// Copyright (c) 2026 Sebastian Klemm
// SPDX-License-Identifier: MIT
//! Tera template registry for full-stack code generation.
//!
//! All templates are embedded as string constants and registered into a
//! shared `Tera` engine at startup.

use tera::Tera;

/// Build the shared Tera template engine with all code generation templates.
pub fn build_engine() -> Result<Tera, tera::Error> {
    let mut tera = Tera::default();

    tera.add_raw_template("backend_cargo_toml", BACKEND_CARGO_TOML)?;
    tera.add_raw_template("main_rs", MAIN_RS)?;
    tera.add_raw_template("config_rs", CONFIG_RS)?;
    tera.add_raw_template("model_rs", MODEL_RS)?;
    tera.add_raw_template("migration_sql", MIGRATION_SQL)?;
    tera.add_raw_template("queries_rs", QUERIES_RS)?;
    tera.add_raw_template("pool_rs", POOL_RS)?;
    tera.add_raw_template("service_rs", SERVICE_RS)?;
    tera.add_raw_template("api_rs", API_RS)?;
    tera.add_raw_template("index_html", INDEX_HTML)?;
    tera.add_raw_template("app_js", APP_JS)?;
    tera.add_raw_template("page_js", PAGE_JS)?;
    tera.add_raw_template("client_js", CLIENT_JS)?;
    tera.add_raw_template("style_css", STYLE_CSS)?;
    tera.add_raw_template("integration_test_rs", INTEGRATION_TEST_RS)?;
    tera.add_raw_template("docker_compose", DOCKER_COMPOSE)?;
    tera.add_raw_template("dockerfile_backend", DOCKERFILE_BACKEND)?;
    tera.add_raw_template("env_example", ENV_EXAMPLE)?;
    tera.add_raw_template("gitignore", GITIGNORE)?;
    tera.add_raw_template("readme_md", README_MD)?;

    Ok(tera)
}

// ─── Rust Backend Templates ───────────────────────────────────────────────────

const BACKEND_CARGO_TOML: &str = r#"[package]
name = "{{ app_name }}"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-rt = "2"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-native-tls", "chrono", "uuid"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = "0.3"
jsonwebtoken = "9"
bcrypt = "0.15"
actix-cors = "0.7"

[dev-dependencies]
actix-web = { version = "4", features = ["macros"] }

[workspace]
"#;

const MAIN_RS: &str = r#"// {{ app_name }} — Generated by ISLS Full-Stack Autonomy
// Copyright (c) 2026 Sebastian Klemm — MIT License

use actix_web::{middleware, web, App, HttpServer};
use dotenv::dotenv;
use std::env;

mod config;
mod models;
mod database;
mod services;
mod api;
mod errors;

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    dotenv().ok();
    tracing_subscriber::fmt::init();

    let config = config::AppConfig::from_env().expect("Failed to load config");
    let pool = database::pool::create_pool(&config.database_url)
        .await
        .expect("Failed to create database pool");

    database::pool::run_migrations(&pool).await.expect("Failed to run migrations");

    let port = config.port;
    tracing::info!("Starting {{ app_name }} on port {}", port);

    HttpServer::new(move || {
        let cors = actix_cors::Cors::default()
            .allow_any_origin()
            .allow_any_method()
            .allow_any_header();

        App::new()
            .wrap(middleware::Logger::default())
            .wrap(cors)
            .app_data(web::Data::new(pool.clone()))
            .app_data(web::Data::new(config.clone()))
            .configure(api::configure_routes)
    })
    .bind(("0.0.0.0", port))?
    .run()
    .await
}
"#;

const CONFIG_RS: &str = r#"// Configuration — {{ app_name }}

use std::env;

#[derive(Clone, Debug)]
pub struct AppConfig {
    pub database_url: String,
    pub port: u16,
    pub jwt_secret: String,
}

impl AppConfig {
    pub fn from_env() -> Result<Self, String> {
        Ok(Self {
            database_url: env::var("DATABASE_URL")
                .unwrap_or_else(|_| "postgres://postgres:postgres@localhost/{{ app_name | replace(from="-", to="_") }}".to_string()),
            port: env::var("PORT")
                .ok()
                .and_then(|p| p.parse().ok())
                .unwrap_or(8080),
            jwt_secret: env::var("JWT_SECRET")
                .unwrap_or_else(|_| "change-me-in-production".to_string()),
        })
    }
}
"#;

const MODEL_RS: &str = r#"// Model: {{ entity }} — generated by ISLS
use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

/// {{ entity }} entity.
#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct {{ entity }} {
    pub id: i64,
    pub name: String,
    pub description: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Payload for creating a new {{ entity }}.
#[derive(Debug, Clone, Deserialize)]
pub struct Create{{ entity }} {
    pub name: String,
    pub description: Option<String>,
}

/// Payload for updating an existing {{ entity }}.
#[derive(Debug, Clone, Deserialize)]
pub struct Update{{ entity }} {
    pub name: Option<String>,
    pub description: Option<String>,
}

impl {{ entity }} {
    /// Validate the entity fields.
    pub fn validate(name: &str) -> Result<(), String> {
        if name.trim().is_empty() {
            return Err("name must not be empty".to_string());
        }
        if name.len() > 255 {
            return Err("name must be at most 255 characters".to_string());
        }
        Ok(())
    }
}
"#;

const MIGRATION_SQL: &str = r#"-- Migration: {{ app_name }} initial schema
-- Generated by ISLS Full-Stack Autonomy

{% for entity in entities %}
CREATE TABLE IF NOT EXISTS {{ entity | lower }}s (
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_{{ entity | lower }}s_name ON {{ entity | lower }}s(name);

{% endfor %}
"#;

const QUERIES_RS: &str = r#"// Database queries: {{ module }} — generated by ISLS
use sqlx::PgPool;
use crate::models::*;

{% for entity in entities %}
/// List all {{ entity }}s.
pub async fn list_{{ entity | lower }}s(pool: &PgPool) -> Result<Vec<{{ entity }}>, sqlx::Error> {
    sqlx::query_as::<_, {{ entity }}>(
        "SELECT id, name, description, created_at, updated_at FROM {{ entity | lower }}s ORDER BY id"
    )
    .fetch_all(pool)
    .await
}

/// Get a {{ entity }} by id.
pub async fn get_{{ entity | lower }}(pool: &PgPool, id: i64) -> Result<Option<{{ entity }}>, sqlx::Error> {
    sqlx::query_as::<_, {{ entity }}>(
        "SELECT id, name, description, created_at, updated_at FROM {{ entity | lower }}s WHERE id = $1"
    )
    .bind(id)
    .fetch_optional(pool)
    .await
}

/// Create a new {{ entity }}.
pub async fn create_{{ entity | lower }}(pool: &PgPool, payload: &Create{{ entity }}) -> Result<{{ entity }}, sqlx::Error> {
    sqlx::query_as::<_, {{ entity }}>(
        "INSERT INTO {{ entity | lower }}s (name, description, created_at, updated_at) \
         VALUES ($1, $2, NOW(), NOW()) \
         RETURNING id, name, description, created_at, updated_at"
    )
    .bind(&payload.name)
    .bind(payload.description.as_deref())
    .fetch_one(pool)
    .await
}

/// Update a {{ entity }}.
pub async fn update_{{ entity | lower }}(pool: &PgPool, id: i64, payload: &Update{{ entity }}) -> Result<Option<{{ entity }}>, sqlx::Error> {
    sqlx::query_as::<_, {{ entity }}>(
        "UPDATE {{ entity | lower }}s \
         SET name = COALESCE($1, name), \
             description = COALESCE($2, description), \
             updated_at = NOW() \
         WHERE id = $3 \
         RETURNING id, name, description, created_at, updated_at"
    )
    .bind(payload.name.as_deref())
    .bind(payload.description.as_deref())
    .bind(id)
    .fetch_optional(pool)
    .await
}

/// Delete a {{ entity }}.
pub async fn delete_{{ entity | lower }}(pool: &PgPool, id: i64) -> Result<bool, sqlx::Error> {
    let result = sqlx::query("DELETE FROM {{ entity | lower }}s WHERE id = $1")
        .bind(id)
        .execute(pool)
        .await?;
    Ok(result.rows_affected() > 0)
}

{% endfor %}
"#;

const POOL_RS: &str = r#"// Database pool — generated by ISLS
use sqlx::{PgPool, postgres::PgPoolOptions};

/// Create a connection pool from the given database URL.
pub async fn create_pool(database_url: &str) -> Result<PgPool, sqlx::Error> {
    PgPoolOptions::new()
        .max_connections(10)
        .connect(database_url)
        .await
}

/// Run embedded SQL migrations.
pub async fn run_migrations(pool: &PgPool) -> Result<(), sqlx::Error> {
    sqlx::migrate!("./migrations").run(pool).await.map_err(|e| {
        sqlx::Error::Configuration(e.to_string().into())
    })
}
"#;

const SERVICE_RS: &str = r#"// Service: {{ module }} — generated by ISLS
use sqlx::PgPool;
use crate::models::*;
use crate::database::{{ module }}_queries as queries;

{% for entity in entities %}
/// List all {{ entity }}s.
pub async fn list_{{ entity | lower }}s(pool: &PgPool) -> Result<Vec<{{ entity }}>, String> {
    queries::list_{{ entity | lower }}s(pool).await.map_err(|e| e.to_string())
}

/// Get a single {{ entity }} by id.
pub async fn get_{{ entity | lower }}(pool: &PgPool, id: i64) -> Result<Option<{{ entity }}>, String> {
    queries::get_{{ entity | lower }}(pool, id).await.map_err(|e| e.to_string())
}

/// Create a new {{ entity }}.
pub async fn create_{{ entity | lower }}(pool: &PgPool, payload: Create{{ entity }}) -> Result<{{ entity }}, String> {
    {{ entity }}::validate(&payload.name)?;
    queries::create_{{ entity | lower }}(pool, &payload).await.map_err(|e| e.to_string())
}

/// Update an existing {{ entity }}.
pub async fn update_{{ entity | lower }}(pool: &PgPool, id: i64, payload: Update{{ entity }}) -> Result<Option<{{ entity }}>, String> {
    if let Some(name) = &payload.name {
        {{ entity }}::validate(name)?;
    }
    queries::update_{{ entity | lower }}(pool, id, &payload).await.map_err(|e| e.to_string())
}

/// Delete a {{ entity }}.
pub async fn delete_{{ entity | lower }}(pool: &PgPool, id: i64) -> Result<bool, String> {
    queries::delete_{{ entity | lower }}(pool, id).await.map_err(|e| e.to_string())
}

{% endfor %}
"#;

const API_RS: &str = r#"// API handlers: {{ module }} — generated by ISLS
use actix_web::{web, HttpResponse, Responder};
use sqlx::PgPool;
use crate::models::*;
use crate::services::{{ module }} as svc;

{% for entity in entities %}
/// GET /api/{{ entity | lower }}s — list all {{ entity }}s
pub async fn list_{{ entity | lower }}s(pool: web::Data<PgPool>) -> impl Responder {
    match svc::list_{{ entity | lower }}s(&pool).await {
        Ok(items) => HttpResponse::Ok().json(items),
        Err(e) => HttpResponse::InternalServerError().json(serde_json::json!({"error": e})),
    }
}

/// GET /api/{{ entity | lower }}s/{id} — get a {{ entity }}
pub async fn get_{{ entity | lower }}(
    pool: web::Data<PgPool>,
    path: web::Path<i64>,
) -> impl Responder {
    let id = path.into_inner();
    match svc::get_{{ entity | lower }}(&pool, id).await {
        Ok(Some(item)) => HttpResponse::Ok().json(item),
        Ok(None) => HttpResponse::NotFound().json(serde_json::json!({"error": "not found"})),
        Err(e) => HttpResponse::InternalServerError().json(serde_json::json!({"error": e})),
    }
}

/// POST /api/{{ entity | lower }}s — create a {{ entity }}
pub async fn create_{{ entity | lower }}(
    pool: web::Data<PgPool>,
    body: web::Json<Create{{ entity }}>,
) -> impl Responder {
    match svc::create_{{ entity | lower }}(&pool, body.into_inner()).await {
        Ok(item) => HttpResponse::Created().json(item),
        Err(e) => HttpResponse::BadRequest().json(serde_json::json!({"error": e})),
    }
}

/// PUT /api/{{ entity | lower }}s/{id} — update a {{ entity }}
pub async fn update_{{ entity | lower }}(
    pool: web::Data<PgPool>,
    path: web::Path<i64>,
    body: web::Json<Update{{ entity }}>,
) -> impl Responder {
    let id = path.into_inner();
    match svc::update_{{ entity | lower }}(&pool, id, body.into_inner()).await {
        Ok(Some(item)) => HttpResponse::Ok().json(item),
        Ok(None) => HttpResponse::NotFound().json(serde_json::json!({"error": "not found"})),
        Err(e) => HttpResponse::BadRequest().json(serde_json::json!({"error": e})),
    }
}

/// DELETE /api/{{ entity | lower }}s/{id} — delete a {{ entity }}
pub async fn delete_{{ entity | lower }}(
    pool: web::Data<PgPool>,
    path: web::Path<i64>,
) -> impl Responder {
    let id = path.into_inner();
    match svc::delete_{{ entity | lower }}(&pool, id).await {
        Ok(true) => HttpResponse::NoContent().finish(),
        Ok(false) => HttpResponse::NotFound().json(serde_json::json!({"error": "not found"})),
        Err(e) => HttpResponse::InternalServerError().json(serde_json::json!({"error": e})),
    }
}

{% endfor %}

/// Register all {{ module }} routes.
pub fn configure(cfg: &mut web::ServiceConfig) {
    {% for entity in entities %}
    cfg.service(
        web::scope("/api/{{ entity | lower }}s")
            .route("", web::get().to(list_{{ entity | lower }}s))
            .route("", web::post().to(create_{{ entity | lower }}))
            .route("/{id}", web::get().to(get_{{ entity | lower }}))
            .route("/{id}", web::put().to(update_{{ entity | lower }}))
            .route("/{id}", web::delete().to(delete_{{ entity | lower }}))
    );
    {% endfor %}
}
"#;

// ─── Frontend Templates ───────────────────────────────────────────────────────

const INDEX_HTML: &str = r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{ app_name }}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <nav class="navbar">
    <a href="/" class="nav-brand">{{ app_name }}</a>
    <ul class="nav-links">
      <li><a href="/" data-route="/">Dashboard</a></li>
      {% for module in modules %}
      <li><a href="/{{ module }}" data-route="/{{ module }}">{{ module | title }}</a></li>
      {% endfor %}
    </ul>
  </nav>
  <main id="app">Loading...</main>
  <script type="module" src="src/app.js"></script>
</body>
</html>
"#;

const APP_JS: &str = r#"// {{ app_name }} — SPA Router — generated by ISLS
import { API_BASE } from './api/client.js';

{% for module in modules %}
import { render as render_{{ module }} } from './pages/{{ module }}.js';
{% endfor %}
import { render as renderDashboard } from './pages/dashboard.js';

const routes = {
  '/': renderDashboard,
  {% for module in modules %}
  '/{{ module }}': render_{{ module }},
  {% endfor %}
};

function navigate(path) {
  const render = routes[path] || renderDashboard;
  document.getElementById('app').innerHTML = '';
  render(document.getElementById('app'));
  document.querySelectorAll('[data-route]').forEach(el => {
    el.classList.toggle('active', el.dataset.route === path);
  });
}

document.querySelectorAll('[data-route]').forEach(el => {
  el.addEventListener('click', e => {
    e.preventDefault();
    const path = el.dataset.route;
    window.history.pushState({}, '', path);
    navigate(path);
  });
});

window.addEventListener('popstate', () => navigate(window.location.pathname));
navigate(window.location.pathname);
"#;

const PAGE_JS: &str = r#"// Page: {{ module }} — generated by ISLS
import { apiFetch } from '../api/client.js';

export async function render(container) {
  container.innerHTML = `
    <div class="page">
      <h1>{{ module | title }}</h1>
      <div class="toolbar">
        <button id="btn-create-{{ module }}">+ New</button>
      </div>
      <div id="{{ module }}-list" class="data-table-wrapper">Loading...</div>
      <div id="{{ module }}-form" class="form-panel" style="display:none"></div>
    </div>
  `;

  await loadList();

  document.getElementById('btn-create-{{ module }}').addEventListener('click', () => showForm());

  async function loadList() {
    const items = await apiFetch('/api/{{ primary_entity | lower }}s');
    const wrapper = document.getElementById('{{ module }}-list');
    if (!items || items.length === 0) {
      wrapper.innerHTML = '<p class="empty-state">No items found.</p>';
      return;
    }
    wrapper.innerHTML = `
      <table class="data-table">
        <thead><tr>
          <th>ID</th><th>Name</th><th>Description</th><th>Actions</th>
        </tr></thead>
        <tbody>${items.map(item => `
          <tr>
            <td>${item.id}</td>
            <td>${item.name || ''}</td>
            <td>${item.description || ''}</td>
            <td>
              <button onclick="editItem(${item.id})">Edit</button>
              <button onclick="deleteItem(${item.id})">Delete</button>
            </td>
          </tr>`).join('')}
        </tbody>
      </table>`;
  }

  function showForm(item = null) {
    const panel = document.getElementById('{{ module }}-form');
    panel.style.display = 'block';
    panel.innerHTML = `
      <form id="entity-form">
        <h2>${item ? 'Edit' : 'New'} {{ primary_entity }}</h2>
        <label>Name<input name="name" value="${item?.name || ''}" required /></label>
        <label>Description<textarea name="description">${item?.description || ''}</textarea></label>
        <div class="form-actions">
          <button type="submit">${item ? 'Update' : 'Create'}</button>
          <button type="button" id="cancel-form">Cancel</button>
        </div>
      </form>`;
    document.getElementById('cancel-form').addEventListener('click', () => { panel.style.display = 'none'; });
    document.getElementById('entity-form').addEventListener('submit', async e => {
      e.preventDefault();
      const data = Object.fromEntries(new FormData(e.target));
      if (item) {
        await apiFetch(`/api/{{ primary_entity | lower }}s/${item.id}`, { method: 'PUT', body: JSON.stringify(data) });
      } else {
        await apiFetch('/api/{{ primary_entity | lower }}s', { method: 'POST', body: JSON.stringify(data) });
      }
      panel.style.display = 'none';
      await loadList();
    });
  }

  window.editItem = async (id) => {
    const item = await apiFetch(`/api/{{ primary_entity | lower }}s/${id}`);
    showForm(item);
  };

  window.deleteItem = async (id) => {
    if (!confirm('Delete this item?')) return;
    await apiFetch(`/api/{{ primary_entity | lower }}s/${id}`, { method: 'DELETE' });
    await loadList();
  };
}
"#;

const CLIENT_JS: &str = r#"// API Client — generated by ISLS
export const API_BASE = 'http://localhost:8080';

export async function apiFetch(path, options = {}) {
  const token = localStorage.getItem('jwt_token');
  const headers = {
    'Content-Type': 'application/json',
    ...(token ? { 'Authorization': `Bearer ${token}` } : {}),
    ...(options.headers || {}),
  };
  try {
    const response = await fetch(`${API_BASE}${path}`, { ...options, headers });
    if (response.status === 204) return null;
    if (!response.ok) {
      const err = await response.json().catch(() => ({ error: response.statusText }));
      throw new Error(err.error || `HTTP ${response.status}`);
    }
    return response.json();
  } catch (e) {
    console.error(`API error for ${path}:`, e);
    throw e;
  }
}
"#;

const STYLE_CSS: &str = r#"/* {{ app_name }} — Minimal CSS — generated by ISLS */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  background: #f5f5f5;
  color: #333;
  line-height: 1.5;
}

.navbar {
  background: #1a1a2e;
  color: white;
  padding: 0.75rem 1.5rem;
  display: flex;
  align-items: center;
  gap: 2rem;
}

.nav-brand { color: white; text-decoration: none; font-weight: 700; font-size: 1.1rem; }
.nav-links { list-style: none; display: flex; gap: 1rem; }
.nav-links a { color: rgba(255,255,255,0.8); text-decoration: none; padding: 0.25rem 0.5rem; border-radius: 4px; }
.nav-links a:hover, .nav-links a.active { background: rgba(255,255,255,0.1); color: white; }

main { padding: 1.5rem; max-width: 1200px; margin: 0 auto; }

.page h1 { margin-bottom: 1rem; font-size: 1.5rem; }
.toolbar { margin-bottom: 1rem; }
button { padding: 0.4rem 0.9rem; border: none; border-radius: 4px; cursor: pointer; background: #1a1a2e; color: white; font-size: 0.9rem; }
button:hover { opacity: 0.85; }

.data-table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
.data-table th, .data-table td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid #eee; }
.data-table th { background: #f8f8f8; font-weight: 600; font-size: 0.875rem; }
.data-table td button { margin-right: 0.5rem; padding: 0.25rem 0.5rem; font-size: 0.8rem; }

.form-panel { background: white; border-radius: 8px; padding: 1.5rem; margin-top: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); max-width: 500px; }
.form-panel h2 { margin-bottom: 1rem; }
label { display: block; margin-bottom: 0.75rem; font-size: 0.9rem; }
label input, label textarea, label select { display: block; width: 100%; margin-top: 0.25rem; padding: 0.5rem; border: 1px solid #ddd; border-radius: 4px; font-size: 0.9rem; }
.form-actions { margin-top: 1rem; display: flex; gap: 0.5rem; }

.empty-state { color: #888; font-style: italic; padding: 1rem 0; }
"#;

// ─── Test Template ─────────────────────────────────────────────────────────────

const INTEGRATION_TEST_RS: &str = r#"// Integration tests: {{ module }} — generated by ISLS
use actix_web::{test, web, App};
use sqlx::PgPool;

// NOTE: These tests require a running PostgreSQL database.
// Set DATABASE_URL env var before running.

{% for entity in entities %}
#[actix_web::test]
async fn test_{{ entity | lower }}_crud() {
    // Setup: this test requires a database connection
    // Run with: DATABASE_URL=postgres://... cargo test
    let database_url = std::env::var("DATABASE_URL")
        .unwrap_or_else(|_| "postgres://postgres:postgres@localhost/{{ app_name | replace(from="-", to="_") }}_test".to_string());

    if let Ok(pool) = sqlx::PgPool::connect(&database_url).await {
        // Create
        let app = test::init_service(
            App::new()
                .app_data(web::Data::new(pool.clone()))
                .configure(crate::api::configure_routes)
        ).await;

        let req = test::TestRequest::post()
            .uri("/api/{{ entity | lower }}s")
            .set_json(serde_json::json!({
                "name": "Test {{ entity }}",
                "description": "Integration test item"
            }))
            .to_request();
        let resp = test::call_service(&app, req).await;
        assert!(resp.status().is_success(), "Create {{ entity }} should succeed");
    } else {
        // Skip if no database available
        eprintln!("Skipping {{ entity }} integration test — no database connection");
    }
}

{% endfor %}
"#;

// ─── Deployment Templates ─────────────────────────────────────────────────────

const DOCKER_COMPOSE: &str = r#"version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: {{ app_name | replace(from="-", to="_") }}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:${DB_PASSWORD:-postgres}@db/{{ app_name | replace(from="-", to="_") }}
      PORT: 8080
      JWT_SECRET: ${JWT_SECRET:-change-in-production}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

volumes:
  pgdata:
"#;

const DOCKERFILE_BACKEND: &str = r#"FROM rust:1.80-slim AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo 'fn main() {}' > src/main.rs
RUN cargo build --release && rm -rf src
COPY src ./src
RUN touch src/main.rs && cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates libssl3 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/{{ app_name }} /usr/local/bin/app
EXPOSE 8080
CMD ["app"]
"#;

const ENV_EXAMPLE: &str = r#"# {{ app_name }} environment configuration
DATABASE_URL=postgres://postgres:postgres@localhost/{{ app_name | replace(from="-", to="_") }}
PORT=8080
JWT_SECRET=change-me-to-a-secure-random-string
DB_PASSWORD=postgres
"#;

const GITIGNORE: &str = r#"/target/
.env
*.pdb
"#;

const README_MD: &str = r#"# {{ app_name }}

Generated by [ISLS Full-Stack Autonomy](https://github.com/LashSesh/graphity).

## Quick Start

### With Docker Compose

```bash
cp .env.example .env
# Edit .env and set a secure DB_PASSWORD and JWT_SECRET
docker-compose up -d
```

The backend API will be available at http://localhost:8080.
The frontend will be available at http://localhost:3000.

### Without Docker

**Requirements:** Rust 1.80+, PostgreSQL 14+

```bash
# Set up environment
cp .env.example .env
# Edit .env with your database URL

# Run migrations and start the backend
cd backend
cargo run

# Serve the frontend
cd ../frontend
python3 -m http.server 3000
```

## API Endpoints

{% for module in modules %}
### {{ module | title }}

{% for entity in modules %}
- `GET /api/{{ entity | lower }}s` — List all
- `POST /api/{{ entity | lower }}s` — Create
- `GET /api/{{ entity | lower }}s/{id}` — Get by ID
- `PUT /api/{{ entity | lower }}s/{id}` — Update
- `DELETE /api/{{ entity | lower }}s/{id}` — Delete
{% endfor %}

{% endfor %}

## Evidence Chain

The `evidence/` directory contains cryptographic proof of the generation process:

- `generation_manifest.json` — what was generated, in what order
- `crystal_registry.json` — all blueprints produced
- `constraint_proof.json` — SHA-256 chain verifying constraints were met

---
*Generated by ISLS Full-Stack Autonomy — © 2026 Sebastian Klemm — MIT License*
"#;

// ═══════════════════════════════════════════════════════════════════════════
// V2 TEMPLATES — Production-quality with rich domain models
// ═══════════════════════════════════════════════════════════════════════════

/// Build a Tera engine with all v2 production-quality templates.
pub fn build_engine_v2() -> Result<Tera, tera::Error> {
    let mut tera = Tera::default();

    tera.add_raw_template("v2_model_rs", V2_MODEL_RS)?;
    tera.add_raw_template("v2_errors_rs", V2_ERRORS_RS)?;
    tera.add_raw_template("v2_pagination_rs", V2_PAGINATION_RS)?;
    tera.add_raw_template("v2_auth_rs", V2_AUTH_RS)?;
    tera.add_raw_template("v2_queries_rs", V2_QUERIES_RS)?;
    tera.add_raw_template("v2_service_rs", V2_SERVICE_RS)?;
    tera.add_raw_template("v2_api_rs", V2_API_RS)?;
    tera.add_raw_template("v2_frontend_page_js", V2_FRONTEND_PAGE_JS)?;
    tera.add_raw_template("v2_frontend_dashboard_js", V2_FRONTEND_DASHBOARD_JS)?;
    tera.add_raw_template("v2_frontend_login_js", V2_FRONTEND_LOGIN_JS)?;
    tera.add_raw_template("v2_frontend_client_js", V2_FRONTEND_CLIENT_JS)?;
    tera.add_raw_template("v2_frontend_index_html", V2_FRONTEND_INDEX_HTML)?;
    tera.add_raw_template("v2_frontend_style_css", V2_FRONTEND_STYLE_CSS)?;
    tera.add_raw_template("v2_config_rs", V2_CONFIG_RS)?;
    tera.add_raw_template("v2_main_rs", V2_MAIN_RS)?;
    tera.add_raw_template("v2_migration_sql", V2_MIGRATION_SQL)?;
    tera.add_raw_template("v2_cargo_toml", V2_CARGO_TOML)?;
    tera.add_raw_template("v2_dockerfile", V2_DOCKERFILE)?;
    tera.add_raw_template("v2_docker_compose", V2_DOCKER_COMPOSE)?;
    tera.add_raw_template("v2_env_example", V2_ENV_EXAMPLE)?;
    tera.add_raw_template("v2_readme_md", V2_README_MD)?;
    tera.add_raw_template("v2_integration_test_rs", V2_INTEGRATION_TEST_RS)?;
    tera.add_raw_template("v2_pool_rs", V2_POOL_RS)?;
    tera.add_raw_template("v2_mod_models_rs", V2_MOD_MODELS_RS)?;
    tera.add_raw_template("v2_mod_database_rs", V2_MOD_DATABASE_RS)?;
    tera.add_raw_template("v2_mod_services_rs", V2_MOD_SERVICES_RS)?;
    tera.add_raw_template("v2_mod_api_rs", V2_MOD_API_RS)?;

    Ok(tera)
}

// ─── V2 Template 1: Model ────────────────────────────────────────────────────

const V2_MODEL_RS: &str = r#"// Model: {{ entity_name }} — generated by ISLS v2
// Copyright (c) 2026 Sebastian Klemm — MIT License

use serde::{Deserialize, Serialize};

/// {{ entity_description }}
#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct {{ entity_name }} {
{% for field in fields %}    pub {{ field.name }}: {{ field.rust_type }},
{% endfor %}}

/// Payload for creating a new {{ entity_name }}.
#[derive(Debug, Clone, Deserialize)]
pub struct Create{{ entity_name }} {
{% for field in create_fields %}    pub {{ field.name }}: {{ field.rust_type }},
{% endfor %}}

/// Payload for updating an existing {{ entity_name }}.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct Update{{ entity_name }} {
{% for field in update_fields %}    pub {{ field.name }}: Option<{{ field.base_type }}>,
{% endfor %}}

impl Create{{ entity_name }} {
    /// Validate all fields before creation.
    pub fn validate(&self) -> Result<(), Vec<String>> {
        let mut errors = Vec::new();
{% for v in validations %}        if !({{ v.condition }}) {
            errors.push("{{ v.message }}".to_string());
        }
{% endfor %}        if errors.is_empty() { Ok(()) } else { Err(errors) }
    }
}
"#;

// Remaining v2 template constants are defined below and added incrementally.
// ─── V2 Template 2: Errors ────────────────────────────────────────────────────

const V2_ERRORS_RS: &str = r#"// Error types — generated by ISLS v2
// Copyright (c) 2026 Sebastian Klemm — MIT License

use actix_web::{HttpResponse, ResponseError};
use std::fmt;

/// Application error type with HTTP status mapping.
#[derive(Debug)]
pub enum AppError {
    /// Resource not found (404).
    NotFound(String),
    /// Bad request / invalid input (400).
    BadRequest(String),
    /// Validation errors (422).
    ValidationError(Vec<String>),
    /// Authentication required (401).
    Unauthorized(String),
    /// Insufficient permissions (403).
    Forbidden(String),
    /// Database error (500).
    DatabaseError(String),
    /// Internal server error (500).
    InternalError(String),
    /// Conflict (409).
    Conflict(String),
}

impl fmt::Display for AppError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            AppError::NotFound(msg) => write!(f, "Not found: {}", msg),
            AppError::BadRequest(msg) => write!(f, "Bad request: {}", msg),
            AppError::ValidationError(errs) => write!(f, "Validation failed: {}", errs.join(", ")),
            AppError::Unauthorized(msg) => write!(f, "Unauthorized: {}", msg),
            AppError::Forbidden(msg) => write!(f, "Forbidden: {}", msg),
            AppError::DatabaseError(msg) => write!(f, "Database error: {}", msg),
            AppError::InternalError(msg) => write!(f, "Internal error: {}", msg),
            AppError::Conflict(msg) => write!(f, "Conflict: {}", msg),
        }
    }
}

impl ResponseError for AppError {
    fn error_response(&self) -> HttpResponse {
        match self {
            AppError::NotFound(msg) => {
                HttpResponse::NotFound().json(serde_json::json!({"error": "not_found", "message": msg}))
            }
            AppError::BadRequest(msg) => {
                HttpResponse::BadRequest().json(serde_json::json!({"error": "bad_request", "message": msg}))
            }
            AppError::ValidationError(errs) => {
                HttpResponse::UnprocessableEntity().json(serde_json::json!({"error": "validation_error", "details": errs}))
            }
            AppError::Unauthorized(msg) => {
                HttpResponse::Unauthorized().json(serde_json::json!({"error": "unauthorized", "message": msg}))
            }
            AppError::Forbidden(msg) => {
                HttpResponse::Forbidden().json(serde_json::json!({"error": "forbidden", "message": msg}))
            }
            AppError::DatabaseError(msg) => {
                HttpResponse::InternalServerError().json(serde_json::json!({"error": "database_error", "message": msg}))
            }
            AppError::InternalError(msg) => {
                HttpResponse::InternalServerError().json(serde_json::json!({"error": "internal_error", "message": msg}))
            }
            AppError::Conflict(msg) => {
                HttpResponse::Conflict().json(serde_json::json!({"error": "conflict", "message": msg}))
            }
        }
    }
}

impl From<sqlx::Error> for AppError {
    fn from(e: sqlx::Error) -> Self {
        match e {
            sqlx::Error::RowNotFound => AppError::NotFound("Resource not found".to_string()),
            _ => AppError::DatabaseError(e.to_string()),
        }
    }
}
"#;
const V2_PAGINATION_RS: &str = r#"// Pagination — generated by ISLS v2
// Copyright (c) 2026 Sebastian Klemm — MIT License

use serde::{Deserialize, Serialize};

/// Query parameters for paginated list endpoints.
#[derive(Debug, Clone, Deserialize)]
pub struct PaginationParams {
    pub page: Option<i64>,
    pub per_page: Option<i64>,
    pub sort: Option<String>,
    pub order: Option<String>,
    pub search: Option<String>,
}

impl PaginationParams {
    /// SQL OFFSET value.
    pub fn offset(&self) -> i64 {
        (self.current_page() - 1) * self.clamped_per_page()
    }

    /// Page number, defaulting to 1.
    pub fn current_page(&self) -> i64 {
        self.page.unwrap_or(1).max(1)
    }

    /// Per-page count clamped to [1, 100], default 25.
    pub fn clamped_per_page(&self) -> i64 {
        self.per_page.unwrap_or(25).clamp(1, 100)
    }

    /// Sort direction: "ASC" or "DESC".
    pub fn sort_direction(&self) -> &str {
        match self.order.as_deref() {
            Some("desc") | Some("DESC") => "DESC",
            _ => "ASC",
        }
    }
}

/// Pagination metadata included in list responses.
#[derive(Debug, Clone, Serialize)]
pub struct PaginationMeta {
    pub page: i64,
    pub per_page: i64,
    pub total: i64,
    pub total_pages: i64,
}

/// Paginated response wrapping data items and metadata.
#[derive(Debug, Clone, Serialize)]
pub struct PaginatedResponse<T: Serialize> {
    pub data: Vec<T>,
    pub pagination: PaginationMeta,
}

impl<T: Serialize> PaginatedResponse<T> {
    /// Build a paginated response from items and total count.
    pub fn new(data: Vec<T>, total: i64, params: &PaginationParams) -> Self {
        let per_page = params.clamped_per_page();
        let total_pages = (total + per_page - 1) / per_page;
        Self {
            data,
            pagination: PaginationMeta {
                page: params.current_page(),
                per_page,
                total,
                total_pages,
            },
        }
    }
}
"#;
const V2_AUTH_RS: &str = r#"// Authentication & authorisation — generated by ISLS v2
// Copyright (c) 2026 Sebastian Klemm — MIT License

use actix_web::{Error, HttpRequest, FromRequest};
use actix_web::web;
use jsonwebtoken::{decode, encode, DecodingKey, EncodingKey, Header, Validation};
use serde::{Deserialize, Serialize};
use std::future::{Ready, ready};

use crate::config::AppConfig;
use crate::errors::AppError;
use crate::models::user::User;

/// JWT claims.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Claims {
    pub sub: i64,
    pub email: String,
    pub role: String,
    pub exp: usize,
    pub iat: usize,
}

/// Create a JWT for a user.
pub fn create_token(user: &User, secret: &str) -> Result<String, AppError> {
    let now = chrono::Utc::now().timestamp() as usize;
    let claims = Claims {
        sub: user.id,
        email: user.email.clone(),
        role: user.role.clone(),
        exp: now + 86400, // 24 hours
        iat: now,
    };
    encode(
        &Header::default(),
        &claims,
        &EncodingKey::from_secret(secret.as_bytes()),
    )
    .map_err(|e| AppError::InternalError(format!("Token creation failed: {}", e)))
}

/// Verify and decode a JWT.
pub fn verify_token(token: &str, secret: &str) -> Result<Claims, AppError> {
    decode::<Claims>(
        token,
        &DecodingKey::from_secret(secret.as_bytes()),
        &Validation::default(),
    )
    .map(|data| data.claims)
    .map_err(|e| AppError::Unauthorized(format!("Invalid token: {}", e)))
}

/// Authenticated user extracted from the Authorization header.
#[derive(Debug, Clone)]
pub struct AuthUser {
    pub id: i64,
    pub email: String,
    pub role: String,
}

impl FromRequest for AuthUser {
    type Error = Error;
    type Future = Ready<Result<Self, Self::Error>>;

    fn from_request(req: &HttpRequest, _: &mut actix_web::dev::Payload) -> Self::Future {
        let config = req.app_data::<web::Data<AppConfig>>().cloned();
        let auth_header = req
            .headers()
            .get("Authorization")
            .and_then(|v| v.to_str().ok())
            .map(|s| s.to_string());

        let result = (|| -> Result<AuthUser, AppError> {
            let header = auth_header.ok_or_else(|| {
                AppError::Unauthorized("Missing Authorization header".to_string())
            })?;
            let token = header
                .strip_prefix("Bearer ")
                .ok_or_else(|| AppError::Unauthorized("Invalid Authorization format".to_string()))?;
            let config = config.ok_or_else(|| {
                AppError::InternalError("AppConfig not found".to_string())
            })?;
            let claims = verify_token(token, &config.jwt_secret)?;
            Ok(AuthUser {
                id: claims.sub,
                email: claims.email,
                role: claims.role,
            })
        })();

        ready(result.map_err(|e| e.into()))
    }
}

/// Check that the user has at least the required role level.
/// Hierarchy: viewer < operator < manager < admin.
pub fn require_role(user: &AuthUser, required: &str) -> Result<(), AppError> {
    let level = |role: &str| -> u8 {
        match role {
            "admin" => 4,
            "manager" => 3,
            "operator" => 2,
            "viewer" => 1,
            _ => 0,
        }
    };
    if level(&user.role) >= level(required) {
        Ok(())
    } else {
        Err(AppError::Forbidden(format!(
            "Role '{}' required, you have '{}'",
            required, user.role
        )))
    }
}

/// Login request payload.
#[derive(Debug, Deserialize)]
pub struct LoginRequest {
    pub email: String,
    pub password: String,
}

/// Login response.
#[derive(Debug, Serialize)]
pub struct LoginResponse {
    pub token: String,
    pub user: AuthUserInfo,
}

/// Public user info returned after login.
#[derive(Debug, Serialize)]
pub struct AuthUserInfo {
    pub id: i64,
    pub email: String,
    pub name: String,
    pub role: String,
}

/// Register request payload.
#[derive(Debug, Deserialize)]
pub struct RegisterRequest {
    pub email: String,
    pub password: String,
    pub name: String,
}
"#;
const V2_QUERIES_RS: &str = r#"// Database queries: {{ entity_snake }} — generated by ISLS v2
// Copyright (c) 2026 Sebastian Klemm — MIT License

use sqlx::PgPool;
use crate::models::{{ entity_snake }}::*;
use crate::pagination::{PaginationParams, PaginatedResponse};

/// List {{ entity_name }}s with pagination, sorting, and search.
pub async fn list(
    pool: &PgPool,
    params: &PaginationParams,
{% for filter in filters %}    {{ filter }}: Option<&str>,
{% endfor %}) -> Result<PaginatedResponse<{{ entity_name }}>, sqlx::Error> {
    let per_page = params.clamped_per_page();
    let offset = params.offset();
{% if search_fields | length > 0 %}    let search_pattern = params.search.as_deref().map(|s| format!("%{}%", s));{% else %}    let _no_search = ();{% endif %}

    // Count total matching rows
    let count_row = sqlx::query_scalar::<_, i64>(
        "SELECT COUNT(*) FROM {{ table_name }} WHERE 1=1\
{% for filter in filters %}         AND (${{ loop.index }}::text IS NULL OR {{ filter }} = ${{ loop.index }})\
{% endfor %}{% if search_fields | length > 0 %}         AND (${{ filters | length + 1 }}::text IS NULL OR ({% for sf in search_fields %}{{ sf }} ILIKE ${{ filters | length + 1 }}{% if not loop.last %} OR {% endif %}{% endfor %}))\
{% endif %}"
    )
{% for filter in filters %}    .bind({{ filter }})
{% endfor %}{% if search_fields | length > 0 %}    .bind(search_pattern.as_deref())
{% endif %}    .fetch_one(pool)
    .await?;

    let total = count_row;

    // Fetch page of results
    let sort_col = params.sort.as_deref().unwrap_or("id");
    let sort_dir = params.sort_direction();
    let order_clause = format!("{} {}", sort_col, sort_dir);

    let rows = sqlx::query_as::<_, {{ entity_name }}>(
        &format!(
            "SELECT {{ select_columns }} FROM {{ table_name }} WHERE 1=1\
{% for filter in filters %}             AND (${{ loop.index }}::text IS NULL OR {{ filter }} = ${{ loop.index }})\
{% endfor %}{% if search_fields | length > 0 %}             AND (${{ filters | length + 1 }}::text IS NULL OR ({% for sf in search_fields %}{{ sf }} ILIKE ${{ filters | length + 1 }}{% if not loop.last %} OR {% endif %}{% endfor %}))\
{% endif %}             ORDER BY {} LIMIT ${} OFFSET ${}",
            order_clause,
            {{ bind_offset_limit_start }},
            {{ bind_offset_limit_start }} + 1
        )
    )
{% for filter in filters %}    .bind({{ filter }})
{% endfor %}{% if search_fields | length > 0 %}    .bind(search_pattern.as_deref())
{% endif %}    .bind(per_page)
    .bind(offset)
    .fetch_all(pool)
    .await?;

    Ok(PaginatedResponse::new(rows, total, params))
}

/// Get a single {{ entity_name }} by id.
pub async fn get_by_id(pool: &PgPool, id: i64) -> Result<{{ entity_name }}, sqlx::Error> {
    sqlx::query_as::<_, {{ entity_name }}>(
        "SELECT {{ select_columns }} FROM {{ table_name }} WHERE id = $1"
    )
    .bind(id)
    .fetch_one(pool)
    .await
}

/// Insert a new {{ entity_name }}.
pub async fn insert(pool: &PgPool, payload: &Create{{ entity_name }}) -> Result<{{ entity_name }}, sqlx::Error> {
    sqlx::query_as::<_, {{ entity_name }}>(
        "INSERT INTO {{ table_name }} ({{ insert_columns }}) \
         VALUES ({{ insert_placeholders }}) \
         RETURNING {{ select_columns }}"
    )
{% for bind in insert_binds %}    .bind({{ bind }})
{% endfor %}    .fetch_one(pool)
    .await
}

/// Update an existing {{ entity_name }}.
pub async fn update(pool: &PgPool, id: i64, payload: &Update{{ entity_name }}) -> Result<{{ entity_name }}, sqlx::Error> {
    sqlx::query_as::<_, {{ entity_name }}>(
        "UPDATE {{ table_name }} SET \
         {{ update_set_clause }}, \
         updated_at = NOW() \
         WHERE id = ${{ update_id_bind }} \
         RETURNING {{ select_columns }}"
    )
{% for bind in update_binds %}    .bind({{ bind }})
{% endfor %}    .bind(id)
    .fetch_one(pool)
    .await
}

/// Delete a {{ entity_name }} by id.
pub async fn delete(pool: &PgPool, id: i64) -> Result<bool, sqlx::Error> {
    let result = sqlx::query("DELETE FROM {{ table_name }} WHERE id = $1")
        .bind(id)
        .execute(pool)
        .await?;
    Ok(result.rows_affected() > 0)
}

{% for extra_query in extra_queries %}{{ extra_query }}
{% endfor %}"#;
const V2_SERVICE_RS: &str = r#"// Service: {{ entity_snake }} — generated by ISLS v2
// Copyright (c) 2026 Sebastian Klemm — MIT License

use sqlx::PgPool;
use crate::auth::{AuthUser, require_role};
use crate::errors::AppError;
use crate::models::{{ entity_snake }}::*;
use crate::database::{{ entity_snake }}_queries as queries;
use crate::pagination::{PaginationParams, PaginatedResponse};

/// List {{ entity_name }}s with pagination.
pub async fn list(
    pool: &PgPool,
    params: &PaginationParams,
    _user: &AuthUser,
{% for filter in filters %}    {{ filter }}: Option<&str>,
{% endfor %}) -> Result<PaginatedResponse<{{ entity_name }}>, AppError> {
    queries::list(pool, params{% for filter in filters %}, {{ filter }}{% endfor %})
        .await
        .map_err(AppError::from)
}

/// Get a single {{ entity_name }}.
pub async fn get(pool: &PgPool, id: i64, _user: &AuthUser) -> Result<{{ entity_name }}, AppError> {
    queries::get_by_id(pool, id)
        .await
        .map_err(AppError::from)
}

/// Create a new {{ entity_name }}.
pub async fn create(
    pool: &PgPool,
    payload: Create{{ entity_name }},
    user: &AuthUser,
) -> Result<{{ entity_name }}, AppError> {
    require_role(user, "operator")?;
    payload.validate().map_err(AppError::ValidationError)?;
    queries::insert(pool, &payload)
        .await
        .map_err(AppError::from)
}

/// Update a {{ entity_name }}.
pub async fn update(
    pool: &PgPool,
    id: i64,
    payload: Update{{ entity_name }},
    user: &AuthUser,
) -> Result<{{ entity_name }}, AppError> {
    require_role(user, "operator")?;
    queries::update(pool, id, &payload)
        .await
        .map_err(AppError::from)
}

/// Delete a {{ entity_name }}.
pub async fn delete(pool: &PgPool, id: i64, user: &AuthUser) -> Result<bool, AppError> {
    require_role(user, "manager")?;
    queries::delete(pool, id)
        .await
        .map_err(AppError::from)
}

{% for rule in business_rules %}{{ rule }}
{% endfor %}"#;
const V2_API_RS: &str = r#"// API handlers: {{ entity_snake }} — generated by ISLS v2
// Copyright (c) 2026 Sebastian Klemm — MIT License

use actix_web::{web, HttpResponse};
use sqlx::PgPool;
use crate::auth::AuthUser;
use crate::models::{{ entity_snake }}::*;
use crate::services::{{ entity_snake }} as svc;
use crate::pagination::PaginationParams;
use crate::errors::AppError;

/// GET /api/{{ table_name }} — list with pagination, filtering, search.
pub async fn list(
    pool: web::Data<PgPool>,
    params: web::Query<PaginationParams>,
    user: AuthUser,
) -> Result<HttpResponse, AppError> {
    let result = svc::list(&pool, &params, &user{% for filter in filters %}, None{% endfor %}).await?;
    Ok(HttpResponse::Ok().json(result))
}

/// GET /api/{{ table_name }}/{id} — get by id.
pub async fn get(
    pool: web::Data<PgPool>,
    path: web::Path<i64>,
    user: AuthUser,
) -> Result<HttpResponse, AppError> {
    let item = svc::get(&pool, path.into_inner(), &user).await?;
    Ok(HttpResponse::Ok().json(item))
}

/// POST /api/{{ table_name }} — create.
pub async fn create(
    pool: web::Data<PgPool>,
    body: web::Json<Create{{ entity_name }}>,
    user: AuthUser,
) -> Result<HttpResponse, AppError> {
    let item = svc::create(&pool, body.into_inner(), &user).await?;
    Ok(HttpResponse::Created().json(item))
}

/// PUT /api/{{ table_name }}/{id} — update.
pub async fn update(
    pool: web::Data<PgPool>,
    path: web::Path<i64>,
    body: web::Json<Update{{ entity_name }}>,
    user: AuthUser,
) -> Result<HttpResponse, AppError> {
    let item = svc::update(&pool, path.into_inner(), body.into_inner(), &user).await?;
    Ok(HttpResponse::Ok().json(item))
}

/// DELETE /api/{{ table_name }}/{id} — delete.
pub async fn delete(
    pool: web::Data<PgPool>,
    path: web::Path<i64>,
    user: AuthUser,
) -> Result<HttpResponse, AppError> {
    let deleted = svc::delete(&pool, path.into_inner(), &user).await?;
    if deleted {
        Ok(HttpResponse::NoContent().finish())
    } else {
        Err(AppError::NotFound("{{ entity_name }} not found".to_string()))
    }
}

{% for extra_handler in extra_handlers %}{{ extra_handler }}
{% endfor %}
/// Register all {{ entity_snake }} routes.
pub fn configure(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/{{ table_name }}")
            .route("", web::get().to(list))
            .route("", web::post().to(create))
            .route("/{id}", web::get().to(get))
            .route("/{id}", web::put().to(update))
            .route("/{id}", web::delete().to(delete))
{% for extra_route in extra_routes %}            {{ extra_route }}
{% endfor %}    );
}
"#;
const V2_FRONTEND_PAGE_JS: &str = r#"// Page: {{ entity_snake }} — generated by ISLS v2
import { apiFetch, getToken } from '../api/client.js';

export async function render(container) {
  let currentPage = 1;
  const perPage = 25;

  container.innerHTML = `
    <div class="page">
      <div class="page-header">
        <h1>{{ entity_name }}s</h1>
        <div class="toolbar">
          <input type="text" id="search-{{ entity_snake }}" placeholder="Search..." class="search-input" />
          <select id="sort-{{ entity_snake }}" class="sort-select">
            <option value="id">ID</option>
{% for col in sortable_columns %}            <option value="{{ col }}">{{ col }}</option>
{% endfor %}          </select>
          <button id="btn-create-{{ entity_snake }}" class="btn btn-primary">+ New {{ entity_name }}</button>
        </div>
      </div>
      <div id="{{ entity_snake }}-list" class="data-table-wrapper">Loading...</div>
      <div id="{{ entity_snake }}-pagination" class="pagination-controls"></div>
      <div id="{{ entity_snake }}-modal" class="modal" style="display:none">
        <div class="modal-content">
          <span class="modal-close" id="close-modal-{{ entity_snake }}">&times;</span>
          <div id="{{ entity_snake }}-form-container"></div>
        </div>
      </div>
    </div>
  `;

  const searchInput = document.getElementById('search-{{ entity_snake }}');
  const sortSelect = document.getElementById('sort-{{ entity_snake }}');
  document.getElementById('btn-create-{{ entity_snake }}').addEventListener('click', () => showForm());
  document.getElementById('close-modal-{{ entity_snake }}').addEventListener('click', closeModal);
  searchInput.addEventListener('input', debounce(() => { currentPage = 1; loadList(); }, 300));
  sortSelect.addEventListener('change', () => loadList());

  await loadList();

  async function loadList() {
    const search = searchInput.value;
    const sort = sortSelect.value;
    const qs = `?page=${currentPage}&per_page=${perPage}&sort=${sort}&order=ASC${search ? '&search=' + encodeURIComponent(search) : ''}`;
    const resp = await apiFetch('/api/{{ table_name }}' + qs);
    const wrapper = document.getElementById('{{ entity_snake }}-list');
    if (!resp || !resp.data || resp.data.length === 0) {
      wrapper.innerHTML = '<p class="empty-state">No {{ entity_name }}s found.</p>';
      document.getElementById('{{ entity_snake }}-pagination').innerHTML = '';
      return;
    }
    wrapper.innerHTML = `
      <table class="data-table">
        <thead><tr>
{% for col in table_columns %}          <th>{{ col }}</th>
{% endfor %}          <th>Actions</th>
        </tr></thead>
        <tbody>${resp.data.map(item => `
          <tr>
{% for col in table_columns %}            <td>${item.{{ col }} != null ? item.{{ col }} : ''}</td>
{% endfor %}            <td class="actions">
              <button class="btn btn-sm" onclick="window.__edit_{{ entity_snake }}(${item.id})">Edit</button>
              <button class="btn btn-sm btn-danger" onclick="window.__delete_{{ entity_snake }}(${item.id})">Delete</button>
            </td>
          </tr>`).join('')}
        </tbody>
      </table>`;

    // Pagination controls
    const pg = resp.pagination;
    const pgEl = document.getElementById('{{ entity_snake }}-pagination');
    pgEl.innerHTML = `
      <span>Page ${pg.page} of ${pg.total_pages} (${pg.total} total)</span>
      <button ${pg.page <= 1 ? 'disabled' : ''} onclick="window.__page_{{ entity_snake }}(${pg.page - 1})">Prev</button>
      <button ${pg.page >= pg.total_pages ? 'disabled' : ''} onclick="window.__page_{{ entity_snake }}(${pg.page + 1})">Next</button>
    `;
  }

  window.__page_{{ entity_snake }} = (p) => { currentPage = p; loadList(); };

  function showForm(item = null) {
    const modal = document.getElementById('{{ entity_snake }}-modal');
    const formContainer = document.getElementById('{{ entity_snake }}-form-container');
    modal.style.display = 'flex';
    formContainer.innerHTML = `
      <form id="form-{{ entity_snake }}">
        <h2>${item ? 'Edit' : 'New'} {{ entity_name }}</h2>
{% for ff in form_fields %}        <div class="form-group">
          <label>{{ ff.label }}</label>
          <input name="{{ ff.name }}" type="{{ ff.input_type }}" value="${item ? (item.{{ ff.name }} || '') : '{{ ff.default }}'}" {% if ff.required %}required{% endif %} />
        </div>
{% endfor %}        <div class="form-actions">
          <button type="submit" class="btn btn-primary">${item ? 'Update' : 'Create'}</button>
          <button type="button" class="btn" onclick="document.getElementById('{{ entity_snake }}-modal').style.display='none'">Cancel</button>
        </div>
      </form>`;
    document.getElementById('form-{{ entity_snake }}').addEventListener('submit', async e => {
      e.preventDefault();
      const data = Object.fromEntries(new FormData(e.target));
      // Convert numeric fields
{% for ff in form_fields %}{% if ff.input_type == "number" %}      if (data.{{ ff.name }}) data.{{ ff.name }} = parseInt(data.{{ ff.name }}, 10);
{% endif %}{% endfor %}      if (item) {
        await apiFetch(`/api/{{ table_name }}/${item.id}`, { method: 'PUT', body: JSON.stringify(data) });
      } else {
        await apiFetch('/api/{{ table_name }}', { method: 'POST', body: JSON.stringify(data) });
      }
      closeModal();
      await loadList();
    });
  }

  function closeModal() {
    document.getElementById('{{ entity_snake }}-modal').style.display = 'none';
  }

  window.__edit_{{ entity_snake }} = async (id) => {
    const item = await apiFetch(`/api/{{ table_name }}/${id}`);
    showForm(item);
  };

  window.__delete_{{ entity_snake }} = async (id) => {
    if (!confirm('Delete this {{ entity_name }}?')) return;
    await apiFetch(`/api/{{ table_name }}/${id}`, { method: 'DELETE' });
    await loadList();
  };
}

function debounce(fn, ms) {
  let timer;
  return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), ms); };
}
"#;
const V2_FRONTEND_DASHBOARD_JS: &str = r#"// Dashboard — generated by ISLS v2
import { apiFetch } from '../api/client.js';

export async function render(container) {
  container.innerHTML = `
    <div class="page">
      <h1>Dashboard</h1>
      <div class="kpi-grid" id="kpi-cards">Loading KPIs...</div>
      <div class="dashboard-charts">
        <div class="chart-card">
          <h3>Orders by Status</h3>
          <canvas id="chart-orders-status" width="400" height="200"></canvas>
        </div>
        <div class="chart-card">
          <h3>Recent Stock Movements</h3>
          <canvas id="chart-stock" width="400" height="200"></canvas>
        </div>
      </div>
      <div class="dashboard-tables">
        <div class="dash-table-card">
          <h3>Recent Orders</h3>
          <div id="recent-orders">Loading...</div>
        </div>
        <div class="dash-table-card">
          <h3>Low Stock Alerts</h3>
          <div id="low-stock-alerts">Loading...</div>
        </div>
      </div>
    </div>
  `;

  // Load KPI data
  try {
    const [products, orders, warehouses] = await Promise.all([
      apiFetch('/api/products?per_page=1'),
      apiFetch('/api/orders?per_page=1'),
      apiFetch('/api/warehouses?per_page=1'),
    ]);

    const kpiEl = document.getElementById('kpi-cards');
    kpiEl.innerHTML = `
      <div class="kpi-card"><div class="kpi-value">${products?.pagination?.total || 0}</div><div class="kpi-label">Products</div></div>
      <div class="kpi-card"><div class="kpi-value">${orders?.pagination?.total || 0}</div><div class="kpi-label">Orders</div></div>
      <div class="kpi-card"><div class="kpi-value">${warehouses?.pagination?.total || 0}</div><div class="kpi-label">Warehouses</div></div>
      <div class="kpi-card kpi-highlight"><div class="kpi-value">Active</div><div class="kpi-label">System Status</div></div>
    `;
  } catch (e) {
    document.getElementById('kpi-cards').innerHTML = '<p>Failed to load KPI data.</p>';
  }

  // Load recent orders
  try {
    const ordersResp = await apiFetch('/api/orders?per_page=5&sort=created_at&order=desc');
    const el = document.getElementById('recent-orders');
    if (ordersResp && ordersResp.data && ordersResp.data.length > 0) {
      el.innerHTML = `<table class="data-table compact"><thead><tr><th>Order #</th><th>Status</th><th>Type</th><th>Total</th></tr></thead><tbody>${
        ordersResp.data.map(o => `<tr><td>${o.order_number}</td><td><span class="badge badge-${o.status}">${o.status}</span></td><td>${o.order_type}</td><td>$${(o.total_amount_cents/100).toFixed(2)}</td></tr>`).join('')
      }</tbody></table>`;
    } else {
      el.innerHTML = '<p class="empty-state">No recent orders.</p>';
    }
  } catch (e) {
    document.getElementById('recent-orders').innerHTML = '<p>Failed to load.</p>';
  }

  // Low stock alerts
  try {
    const productsResp = await apiFetch('/api/products?per_page=100&sort=quantity_on_hand&order=ASC');
    const el = document.getElementById('low-stock-alerts');
    const lowStock = (productsResp?.data || []).filter(p => p.quantity_on_hand <= p.reorder_level && p.is_active);
    if (lowStock.length > 0) {
      el.innerHTML = `<table class="data-table compact"><thead><tr><th>SKU</th><th>Name</th><th>Stock</th><th>Reorder Level</th></tr></thead><tbody>${
        lowStock.slice(0, 10).map(p => `<tr class="row-warning"><td>${p.sku}</td><td>${p.name}</td><td>${p.quantity_on_hand}</td><td>${p.reorder_level}</td></tr>`).join('')
      }</tbody></table>`;
    } else {
      el.innerHTML = '<p class="empty-state">All stock levels OK.</p>';
    }
  } catch (e) {
    document.getElementById('low-stock-alerts').innerHTML = '<p>Failed to load.</p>';
  }

  // Simple bar chart on canvas
  drawBarChart('chart-orders-status', ['pending','confirmed','processing','shipped','delivered'], [0,0,0,0,0]);
  drawBarChart('chart-stock', ['receipt','shipment','adjustment','transfer','return'], [0,0,0,0,0]);
}

function drawBarChart(canvasId, labels, values) {
  const canvas = document.getElementById(canvasId);
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  const w = canvas.width, h = canvas.height;
  const barW = w / (labels.length * 2);
  const maxVal = Math.max(...values, 1);
  const colors = ['#3b82f6','#10b981','#f59e0b','#ef4444','#8b5cf6'];

  ctx.clearRect(0, 0, w, h);
  ctx.fillStyle = '#f3f4f6'; ctx.fillRect(0, 0, w, h);

  labels.forEach((label, i) => {
    const x = (i * 2 + 0.5) * barW;
    const barH = (values[i] / maxVal) * (h - 40);
    ctx.fillStyle = colors[i % colors.length];
    ctx.fillRect(x, h - 30 - barH, barW, barH);
    ctx.fillStyle = '#374151';
    ctx.font = '10px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(label, x + barW / 2, h - 10);
    ctx.fillText(values[i].toString(), x + barW / 2, h - 34 - barH);
  });
}
"#;
const V2_FRONTEND_LOGIN_JS: &str = r##"// Login page — generated by ISLS v2
import { apiFetch, setToken, getToken } from '../api/client.js';

export async function render(container) {
  if (getToken()) {
    container.innerHTML = '<p>Already logged in. <a href="/" data-route="/">Go to Dashboard</a></p>';
    return;
  }
  container.innerHTML = `
    <div class="login-page">
      <div class="login-card">
        <h2>Login</h2>
        <form id="login-form">
          <div class="form-group">
            <label>Email</label>
            <input name="email" type="email" required placeholder="admin@example.com" />
          </div>
          <div class="form-group">
            <label>Password</label>
            <input name="password" type="password" required placeholder="password" />
          </div>
          <div id="login-error" class="error-message" style="display:none"></div>
          <button type="submit" class="btn btn-primary btn-block">Sign In</button>
        </form>
        <p class="login-register">Don't have an account? <a href="#" id="show-register">Register</a></p>
      </div>
    </div>
  `;
  document.getElementById('login-form').addEventListener('submit', async e => {
    e.preventDefault();
    const data = Object.fromEntries(new FormData(e.target));
    try {
      const resp = await apiFetch('/api/auth/login', {
        method: 'POST',
        body: JSON.stringify(data),
        noAuth: true,
      });
      if (resp && resp.token) {
        setToken(resp.token);
        window.history.pushState({}, '', '/');
        window.dispatchEvent(new PopStateEvent('popstate'));
      } else {
        showError('Invalid credentials');
      }
    } catch (err) {
      showError(err.message || 'Login failed');
    }
  });

  function showError(msg) {
    const el = document.getElementById('login-error');
    el.textContent = msg;
    el.style.display = 'block';
  }
}
"##;
const V2_FRONTEND_CLIENT_JS: &str = r#"// API client — generated by ISLS v2
export const API_BASE = '';

export function getToken() {
  return localStorage.getItem('auth_token');
}

export function setToken(token) {
  localStorage.setItem('auth_token', token);
}

export function clearToken() {
  localStorage.removeItem('auth_token');
}

export async function apiFetch(url, options = {}) {
  const headers = { 'Content-Type': 'application/json' };
  const token = getToken();
  if (token && !options.noAuth) {
    headers['Authorization'] = `Bearer ${token}`;
  }
  const resp = await fetch(API_BASE + url, {
    headers,
    ...options,
    headers: { ...headers, ...(options.headers || {}) },
  });
  if (resp.status === 401) {
    clearToken();
    window.history.pushState({}, '', '/login');
    window.dispatchEvent(new PopStateEvent('popstate'));
    throw new Error('Session expired');
  }
  if (resp.status === 204) return null;
  if (!resp.ok) {
    const err = await resp.json().catch(() => ({ message: resp.statusText }));
    throw new Error(err.message || err.error || 'Request failed');
  }
  return resp.json();
}
"#;
const V2_FRONTEND_INDEX_HTML: &str = r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{ app_name }}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <nav class="navbar">
    <a href="/" class="nav-brand">{{ app_name }}</a>
    <ul class="nav-links">
      <li><a href="/" data-route="/">Dashboard</a></li>
{% for page in pages %}      <li><a href="/{{ page.route }}" data-route="/{{ page.route }}">{{ page.label }}</a></li>
{% endfor %}      <li><a href="/login" data-route="/login">Login</a></li>
    </ul>
  </nav>
  <main id="app">Loading...</main>
  <script type="module" src="src/app.js"></script>
</body>
</html>
"#;
const V2_FRONTEND_STYLE_CSS: &str = r#"/* {{ app_name }} — generated by ISLS v2 */
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f3f4f6; color: #1f2937; }

.navbar { display: flex; align-items: center; background: #1e293b; color: #fff; padding: 0 1.5rem; height: 56px; }
.nav-brand { font-weight: 700; font-size: 1.2rem; color: #fff; text-decoration: none; margin-right: 2rem; }
.nav-links { list-style: none; display: flex; gap: 1rem; }
.nav-links a { color: #94a3b8; text-decoration: none; padding: 0.5rem 0.75rem; border-radius: 6px; transition: all 0.2s; }
.nav-links a:hover, .nav-links a.active { color: #fff; background: #334155; }

#app { max-width: 1200px; margin: 1.5rem auto; padding: 0 1rem; }
.page { background: #fff; border-radius: 8px; padding: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
.page-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem; }
.page-header h1 { font-size: 1.5rem; }
.toolbar { display: flex; gap: 0.5rem; align-items: center; }
.search-input { padding: 0.5rem 0.75rem; border: 1px solid #d1d5db; border-radius: 6px; }
.sort-select { padding: 0.5rem; border: 1px solid #d1d5db; border-radius: 6px; }

.btn { padding: 0.5rem 1rem; border: none; border-radius: 6px; cursor: pointer; font-size: 0.875rem; transition: background 0.2s; }
.btn-primary { background: #3b82f6; color: #fff; }
.btn-primary:hover { background: #2563eb; }
.btn-danger { background: #ef4444; color: #fff; }
.btn-danger:hover { background: #dc2626; }
.btn-sm { padding: 0.25rem 0.5rem; font-size: 0.75rem; }
.btn-block { width: 100%; }

.data-table { width: 100%; border-collapse: collapse; }
.data-table th, .data-table td { padding: 0.75rem; text-align: left; border-bottom: 1px solid #e5e7eb; }
.data-table th { background: #f9fafb; font-weight: 600; font-size: 0.8rem; text-transform: uppercase; color: #6b7280; }
.data-table tr:hover { background: #f9fafb; }
.data-table.compact th, .data-table.compact td { padding: 0.5rem; font-size: 0.85rem; }
.actions { display: flex; gap: 0.25rem; }

.pagination-controls { display: flex; align-items: center; gap: 1rem; margin-top: 1rem; justify-content: center; }
.pagination-controls button { padding: 0.4rem 0.8rem; border: 1px solid #d1d5db; background: #fff; border-radius: 4px; cursor: pointer; }
.pagination-controls button:disabled { opacity: 0.5; cursor: not-allowed; }

.modal { display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.5); justify-content: center; align-items: center; z-index: 1000; }
.modal-content { background: #fff; border-radius: 8px; padding: 2rem; width: 90%; max-width: 500px; position: relative; }
.modal-close { position: absolute; top: 0.75rem; right: 1rem; font-size: 1.5rem; cursor: pointer; color: #6b7280; }

.form-group { margin-bottom: 1rem; }
.form-group label { display: block; font-weight: 500; margin-bottom: 0.25rem; font-size: 0.875rem; color: #374151; }
.form-group input, .form-group select, .form-group textarea { width: 100%; padding: 0.5rem 0.75rem; border: 1px solid #d1d5db; border-radius: 6px; font-size: 0.9rem; }
.form-actions { display: flex; gap: 0.5rem; margin-top: 1rem; }

.kpi-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 1.5rem; }
.kpi-card { background: #fff; border-radius: 8px; padding: 1.5rem; text-align: center; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
.kpi-value { font-size: 2rem; font-weight: 700; color: #1e293b; }
.kpi-label { font-size: 0.85rem; color: #6b7280; margin-top: 0.25rem; }
.kpi-highlight { background: #ecfdf5; border: 2px solid #10b981; }
.kpi-highlight .kpi-value { color: #10b981; }

.dashboard-charts { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin-bottom: 1.5rem; }
.chart-card { background: #fff; border-radius: 8px; padding: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
.chart-card h3 { font-size: 1rem; margin-bottom: 0.75rem; }

.dashboard-tables { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
.dash-table-card { background: #fff; border-radius: 8px; padding: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
.dash-table-card h3 { font-size: 1rem; margin-bottom: 0.75rem; }

.badge { padding: 0.2rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: 600; }
.badge-pending { background: #fef3c7; color: #92400e; }
.badge-confirmed { background: #dbeafe; color: #1e40af; }
.badge-processing { background: #e0e7ff; color: #3730a3; }
.badge-shipped { background: #d1fae5; color: #065f46; }
.badge-delivered { background: #ecfdf5; color: #047857; }
.badge-cancelled { background: #fee2e2; color: #991b1b; }
.row-warning { background: #fef3c7 !important; }

.empty-state { text-align: center; padding: 2rem; color: #9ca3af; }
.error-message { background: #fee2e2; color: #991b1b; padding: 0.75rem; border-radius: 6px; margin-bottom: 1rem; }

.login-page { display: flex; justify-content: center; align-items: center; min-height: 60vh; }
.login-card { background: #fff; padding: 2rem; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); width: 100%; max-width: 400px; }
.login-card h2 { margin-bottom: 1.5rem; text-align: center; }
.login-register { text-align: center; margin-top: 1rem; font-size: 0.85rem; color: #6b7280; }

@media (max-width: 768px) {
  .dashboard-charts, .dashboard-tables { grid-template-columns: 1fr; }
  .page-header { flex-direction: column; gap: 0.75rem; }
  .toolbar { flex-wrap: wrap; }
}
"#;
const V2_CONFIG_RS: &str = r#"// Configuration — generated by ISLS v2
// Copyright (c) 2026 Sebastian Klemm — MIT License

use std::env;

/// Application configuration loaded from environment variables.
#[derive(Clone, Debug)]
pub struct AppConfig {
    pub database_url: String,
    pub jwt_secret: String,
    pub server_host: String,
    pub server_port: u16,
    pub log_level: String,
}

impl AppConfig {
    /// Load configuration from environment variables with sensible defaults.
    pub fn from_env() -> Result<Self, String> {
        Ok(Self {
            database_url: env::var("DATABASE_URL")
                .unwrap_or_else(|_| "postgres://postgres:postgres@localhost/{{ app_name_snake }}".to_string()),
            jwt_secret: env::var("JWT_SECRET")
                .unwrap_or_else(|_| "change-me-in-production-{{ app_name_snake }}".to_string()),
            server_host: env::var("SERVER_HOST")
                .unwrap_or_else(|_| "0.0.0.0".to_string()),
            server_port: env::var("SERVER_PORT")
                .ok()
                .and_then(|p| p.parse().ok())
                .unwrap_or(8080),
            log_level: env::var("LOG_LEVEL")
                .unwrap_or_else(|_| "info".to_string()),
        })
    }
}
"#;

const V2_MAIN_RS: &str = r#"// {{ app_name }} — generated by ISLS v2
// Copyright (c) 2026 Sebastian Klemm — MIT License

use actix_web::{middleware, web, App, HttpServer};
use dotenv::dotenv;

mod config;
mod errors;
mod pagination;
mod auth;
mod models;
mod database;
mod services;
mod api;

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    dotenv().ok();
    tracing_subscriber::fmt::init();

    let config = config::AppConfig::from_env().expect("Failed to load config");
    let pool = database::pool::create_pool(&config.database_url)
        .await
        .expect("Failed to create database pool");

    database::pool::run_migrations(&pool).await.expect("Failed to run migrations");

    let port = config.server_port;
    let host = config.server_host.clone();
    tracing::info!("Starting {{ app_name }} on {}:{}", host, port);

    let config_data = web::Data::new(config);

    HttpServer::new(move || {
        let cors = actix_cors::Cors::default()
            .allow_any_origin()
            .allow_any_method()
            .allow_any_header();

        let mut app = App::new()
            .wrap(middleware::Logger::default())
            .wrap(cors)
            .app_data(web::Data::new(pool.clone()))
            .app_data(config_data.clone());

{% for entity_snake in entity_snakes %}        app = app.configure(api::{{ entity_snake }}::configure);
{% endfor %}        app.configure(api::auth_routes::configure)
    })
    .bind((host, port))?
    .run()
    .await
}
"#;

const V2_MIGRATION_SQL: &str = r#"-- Migration: {{ app_name }} initial schema
-- Generated by ISLS v2
-- Copyright (c) 2026 Sebastian Klemm — MIT License

{% for table in tables %}
-- ─── {{ table.entity_name }} ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS {{ table.table_name }} (
{% for col in table.columns %}    {{ col.definition }}{% if not loop.last %},{% endif %}

{% endfor %});

{% for idx in table.indices %}CREATE INDEX IF NOT EXISTS {{ idx.name }} ON {{ table.table_name }}({{ idx.columns }});
{% endfor %}
{% endfor %}"#;

const V2_CARGO_TOML: &str = r#"[package]
name = "{{ app_name }}"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-rt = "2"
actix-cors = "0.7"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-native-tls", "chrono", "uuid"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = "0.3"
jsonwebtoken = "9"
bcrypt = "0.15"

[dev-dependencies]
actix-web = { version = "4", features = ["macros"] }

[workspace]
"#;

const V2_DOCKERFILE: &str = r#"# Dockerfile — generated by ISLS v2
# Multi-stage build for {{ app_name }}

FROM rust:1.82-slim AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release 2>/dev/null || true
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/{{ app_name }} /usr/local/bin/app
EXPOSE 8080
CMD ["app"]
"#;

const V2_DOCKER_COMPOSE: &str = r#"# docker-compose.yml — generated by ISLS v2
version: "3.8"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: {{ app_name_snake }}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/{{ app_name_snake }}
      JWT_SECRET: dev-secret-change-in-production
      SERVER_PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
"#;

const V2_ENV_EXAMPLE: &str = r#"# Environment variables — generated by ISLS v2
# Copy to .env and adjust values

DATABASE_URL=postgres://postgres:postgres@localhost/{{ app_name_snake }}
JWT_SECRET=change-me-in-production
SERVER_HOST=0.0.0.0
SERVER_PORT=8080
LOG_LEVEL=info
"#;

const V2_README_MD: &str = r#"# {{ app_name }}

> Generated by ISLS v2 Full-Stack Autonomy — © 2026 Sebastian Klemm — MIT License

## Quick Start

```bash
# Start database
docker-compose up -d db

# Run backend
cd backend
cp ../.env.example .env
cargo run

# Open frontend
open frontend/index.html
```

## API Endpoints

### Authentication

- `POST /api/auth/login` — Login (returns JWT)
- `POST /api/auth/register` — Register new user

### Resources

{% for entity in entities %}#### {{ entity.name }}
- `GET /api/{{ entity.table }}` — List (paginated, filterable, searchable)
- `GET /api/{{ entity.table }}/{id}` — Get by ID
- `POST /api/{{ entity.table }}` — Create (auth required)
- `PUT /api/{{ entity.table }}/{id}` — Update (auth required)
- `DELETE /api/{{ entity.table }}/{id}` — Delete (manager+ required)
{% endfor %}
### Query Parameters

| Param | Description | Example |
|-------|-------------|---------|
| `page` | Page number (default: 1) | `?page=2` |
| `per_page` | Items per page (1-100, default: 25) | `?per_page=50` |
| `sort` | Sort column | `?sort=created_at` |
| `order` | Sort direction (ASC/DESC) | `?order=desc` |
| `search` | Full-text search | `?search=widget` |

## Architecture

```
backend/
  src/
    main.rs          — Entry point
    config.rs        — Environment configuration
    errors.rs        — Error types with HTTP status mapping
    pagination.rs    — Pagination support
    auth.rs          — JWT authentication
    models/          — Data models (sqlx::FromRow)
    database/        — SQL queries
    services/        — Business logic
    api/             — HTTP handlers
  migrations/        — SQL migrations
frontend/
  index.html         — SPA shell
  style.css          — Styles
  src/
    app.js           — Router
    api/client.js    — API client
    pages/           — Entity pages + dashboard
```
"#;

const V2_INTEGRATION_TEST_RS: &str = r#"// Integration tests — generated by ISLS v2
// Copyright (c) 2026 Sebastian Klemm — MIT License

// These tests require a running PostgreSQL instance.
// Set DATABASE_URL and run: cargo test

#[cfg(test)]
mod tests {
    use actix_web::{test, web, App};
    use sqlx::PgPool;

{% for entity in entities %}    // ── {{ entity.name }} tests ──

    #[actix_web::test]
    async fn test_list_{{ entity.snake }}s_returns_200() {
        // Test that listing {{ entity.snake }}s returns HTTP 200
        // Requires: running database with migrations applied
        assert!(true, "{{ entity.name }} list endpoint placeholder");
    }

    #[actix_web::test]
    async fn test_create_{{ entity.snake }}_returns_201() {
        assert!(true, "{{ entity.name }} create endpoint placeholder");
    }

    #[actix_web::test]
    async fn test_get_nonexistent_{{ entity.snake }}_returns_404() {
        assert!(true, "{{ entity.name }} not-found placeholder");
    }

    #[actix_web::test]
    async fn test_unauthorized_{{ entity.snake }}_returns_401() {
        assert!(true, "{{ entity.name }} auth required placeholder");
    }

{% endfor %}
{% for rule in business_rules %}    // ── Business rule: {{ rule.name }} ──

    #[actix_web::test]
    async fn test_{{ rule.name }}() {
        assert!(true, "Business rule {{ rule.name }} placeholder");
    }

{% endfor %}}
"#;

const V2_POOL_RS: &str = r#"// Database pool — generated by ISLS v2
// Copyright (c) 2026 Sebastian Klemm — MIT License

use sqlx::{PgPool, postgres::PgPoolOptions};

/// Create a connection pool from the given database URL.
pub async fn create_pool(database_url: &str) -> Result<PgPool, sqlx::Error> {
    PgPoolOptions::new()
        .max_connections(10)
        .connect(database_url)
        .await
}

/// Run embedded SQL migrations.
pub async fn run_migrations(pool: &PgPool) -> Result<(), sqlx::Error> {
    sqlx::migrate!("./migrations").run(pool).await.map_err(|e| {
        sqlx::Error::Configuration(e.to_string().into())
    })
}
"#;

const V2_MOD_MODELS_RS: &str = r#"// Models module — generated by ISLS v2
{% for entity_snake in entity_snakes %}pub mod {{ entity_snake }};
{% endfor %}"#;

const V2_MOD_DATABASE_RS: &str = r#"// Database module — generated by ISLS v2
pub mod pool;
{% for entity_snake in entity_snakes %}pub mod {{ entity_snake }}_queries;
{% endfor %}"#;

const V2_MOD_SERVICES_RS: &str = r#"// Services module — generated by ISLS v2
{% for entity_snake in entity_snakes %}pub mod {{ entity_snake }};
{% endfor %}"#;

const V2_MOD_API_RS: &str = r#"// API module — generated by ISLS v2
pub mod auth_routes;
{% for entity_snake in entity_snakes %}pub mod {{ entity_snake }};
{% endfor %}"#;
