// Copyright (c) 2026 Sebastian Klemm
// SPDX-License-Identifier: MIT
//
//! Grammar and language generation for ISLS — condensed from Die Schmiede.
//!
//! Provides grammar-driven code generation capabilities. The core grammar
//! generation (lexer, parser, typechecker, codegen from BNF-like specs) is
//! on the roadmap; this crate provides the stub types and API surface for
//! integration with the pipeline.
//!
//! Note: isls-langgen is not on the critical path for full-stack generation
//! (which generates Rust/JS/SQL from templates, not custom languages). It is
//! included for completeness per the fusion spec.

use serde::{Deserialize, Serialize};
use thiserror::Error;

// ─── Error ───────────────────────────────────────────────────────────────────

#[derive(Debug, Error)]
pub enum LangGenError {
    #[error("grammar rule error: {0}")]
    GrammarRule(String),
    #[error("unsupported target: {0}")]
    UnsupportedTarget(String),
    #[error("generation failed: {0}")]
    GenerationFailed(String),
}

pub type Result<T> = std::result::Result<T, LangGenError>;

// ─── GrammarSpec ─────────────────────────────────────────────────────────────

/// Specification for a grammar to be generated.
///
/// Describes a custom language in terms of its name, production rules,
/// and target code generation backend.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct GrammarSpec {
    /// Language name (used for file naming and token prefix).
    pub name: String,
    /// BNF-like production rules, e.g. `["expr := term ('+' term)*"]`.
    pub rules: Vec<String>,
    /// Target backend for generated code: "rust", "python", "javascript".
    pub target: String,
    /// Whether to generate a lexer alongside the parser.
    pub with_lexer: bool,
    /// Whether to generate a type checker stub.
    pub with_typechecker: bool,
}

impl GrammarSpec {
    /// Create a new grammar spec with default settings.
    pub fn new(name: impl Into<String>, rules: Vec<String>) -> Self {
        Self {
            name: name.into(),
            rules,
            target: "rust".to_string(),
            with_lexer: true,
            with_typechecker: false,
        }
    }
}

// ─── GeneratedGrammar ────────────────────────────────────────────────────────

/// Output of grammar generation — source code artefacts.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct GeneratedGrammar {
    /// Generated lexer source (if requested).
    pub lexer: Option<String>,
    /// Generated parser source.
    pub parser: String,
    /// Generated typechecker stub source (if requested).
    pub typechecker: Option<String>,
    /// Generated codegen stub source.
    pub codegen: String,
}

// ─── Public API ──────────────────────────────────────────────────────────────

/// Generate grammar artefacts from a `GrammarSpec`.
///
/// Currently returns a minimal stub implementation. Full grammar generation
/// from production rules is on the roadmap.
pub fn generate_grammar(spec: &GrammarSpec) -> Result<GeneratedGrammar> {
    if spec.name.is_empty() {
        return Err(LangGenError::GrammarRule("grammar name must not be empty".to_string()));
    }
    if !matches!(spec.target.as_str(), "rust" | "python" | "javascript") {
        return Err(LangGenError::UnsupportedTarget(spec.target.clone()));
    }

    let name = &spec.name;

    let lexer = if spec.with_lexer {
        Some(format!(
            "// {name} lexer — generated by isls-langgen (stub)\n\
             #[derive(Debug, Clone, PartialEq)]\n\
             pub enum {name}Token {{\n\
                 Ident(String),\n\
                 Number(f64),\n\
                 Eof,\n\
             }}\n"
        ))
    } else {
        None
    };

    let parser = format!(
        "// {name} parser — generated by isls-langgen (stub)\n\
         pub struct {name}Parser {{\n\
             pub rules: Vec<String>,\n\
         }}\n\
         impl {name}Parser {{\n\
             pub fn new() -> Self {{ Self {{ rules: vec![] }} }}\n\
             pub fn parse(&self, _input: &str) -> Result<(), String> {{ Ok(()) }}\n\
         }}\n"
    );

    let typechecker = if spec.with_typechecker {
        Some(format!(
            "// {name} typechecker — generated by isls-langgen (stub)\n\
             pub struct {name}TypeChecker;\n\
             impl {name}TypeChecker {{\n\
                 pub fn check(&self, _ast: &()) -> Result<(), String> {{ Ok(()) }}\n\
             }}\n"
        ))
    } else {
        None
    };

    let codegen = format!(
        "// {name} codegen — generated by isls-langgen (stub)\n\
         pub struct {name}CodeGen;\n\
         impl {name}CodeGen {{\n\
             pub fn emit(&self, _ast: &()) -> String {{ String::new() }}\n\
         }}\n"
    );

    Ok(GeneratedGrammar { lexer, parser, typechecker, codegen })
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_basic_grammar() {
        let spec = GrammarSpec::new("Calc", vec![
            "expr := term ('+' term)*".to_string(),
            "term := NUM | '(' expr ')'".to_string(),
        ]);
        let gen = generate_grammar(&spec).unwrap();
        assert!(gen.parser.contains("CalcParser"));
        assert!(gen.lexer.is_some());
    }

    #[test]
    fn reject_empty_name() {
        let spec = GrammarSpec::new("", vec![]);
        assert!(generate_grammar(&spec).is_err());
    }

    #[test]
    fn reject_unsupported_target() {
        let mut spec = GrammarSpec::new("Test", vec![]);
        spec.target = "cobol".to_string();
        assert!(generate_grammar(&spec).is_err());
    }
}
