// Stage 4: LOGIC — Services layer (template CRUD; oracle for complex business logic)
use tera::Context;
use crate::{GenContext, OrchestratorError, Result};
use super::{Stage, StageResult, write_file};
use isls_blueprint::BlueprintRegistry;

pub fn run(
    ctx: &mut GenContext,
    _blueprints: &BlueprintRegistry,
    _mock_oracle: bool,
) -> Result<StageResult> {
    let tera = crate::templates::build_engine()
        .map_err(|e| OrchestratorError::Template(e.to_string()))?;

    let backend_dir = ctx.output_dir.join("backend");
    let mut components_generated = 0;
    let mut blueprint_hits = 0;

    // services/mod.rs
    {
        let mut lines = vec!["// services/mod.rs — generated by ISLS".to_string()];
        for module in &ctx.spec.modules {
            lines.push(format!("pub mod {};", module.name));
        }
        let content = lines.join("\n") + "\n";
        let path = backend_dir.join("src/services/mod.rs");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("logic", path.clone(), &bytes);
        ctx.files_written.push(path);
    }

    // One service file per module — template-based for CRUD
    for module in &ctx.spec.modules {
        let mut tctx = Context::new();
        tctx.insert("module", &module.name);
        tctx.insert("entities", &module.entities);
        tctx.insert("app_name", &ctx.spec.name);

        let content = tera.render("service_rs", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;

        let path = backend_dir.join(format!("src/services/{}.rs", module.name));
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("logic", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
        blueprint_hits += 1; // template-based = blueprint hit
    }

    ctx.blueprint_hits += blueprint_hits;

    let mut result = StageResult::ok(Stage::Logic, components_generated, 0, blueprint_hits);
    result.notes = vec![
        format!("service modules: {}", ctx.spec.modules.iter().map(|m| m.name.as_str()).collect::<Vec<_>>().join(", ")),
        "mode: template-based CRUD (mock oracle)".to_string(),
    ];
    Ok(result)
}
