// Stage 2: MODEL — Architecture → Rust structs + SQL schema (template-driven)
use tera::Context;
use crate::{GenContext, OrchestratorError, Result};
use super::{Stage, StageResult, write_file};
use isls_blueprint::BlueprintRegistry;
use isls_learner::PatternLibrary;
use isls_reader::parse_string;

pub fn run(
    ctx: &mut GenContext,
    _blueprints: &BlueprintRegistry,
    _learner: &mut PatternLibrary,
) -> Result<StageResult> {
    let tera = crate::templates::build_engine()
        .map_err(|e| OrchestratorError::Template(e.to_string()))?;

    let arch = ctx.architecture.as_ref().ok_or_else(|| OrchestratorError::StageFailed {
        stage: Stage::Model,
        reason: "Architecture not set — run Stage 1 first".to_string(),
    })?;

    let backend_dir = ctx.output_dir.join("backend");
    let mut components_generated = 0;

    // Collect all unique entities across modules
    let mut all_entities: Vec<String> = ctx.spec.modules.iter()
        .flat_map(|m| m.entities.iter().cloned())
        .collect();
    all_entities.sort();
    all_entities.dedup();

    // Write models/mod.rs that re-exports all entity modules
    let models_mod_content = {
        let mut lines = vec!["// models/mod.rs — generated by ISLS".to_string()];
        for entity in &all_entities {
            lines.push(format!("pub mod {};", entity.to_lowercase()));
            lines.push(format!("pub use {}::*;", entity.to_lowercase()));
        }
        lines.join("\n") + "\n"
    };
    let models_mod_path = backend_dir.join("src/models/mod.rs");
    let bytes = write_file(&models_mod_path, &models_mod_content)?;
    ctx.evidence.record("model", models_mod_path.clone(), &bytes);
    ctx.files_written.push(models_mod_path);

    // Write one model file per entity
    for entity in &all_entities {
        let mut tctx = Context::new();
        tctx.insert("entity", entity);
        tctx.insert("app_name", &ctx.spec.name);

        let content = tera.render("model_rs", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;

        let path = backend_dir.join(format!("src/models/{}.rs", entity.to_lowercase()));
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("model", path.clone(), &bytes);
        ctx.files_written.push(path.clone());
        components_generated += 1;

        // Feed to learner for pattern accumulation
        if let Ok(obs) = parse_string(&content, isls_reader::Language::Rust) {
            _learner.add_pattern(&format!("{}_model", entity.to_lowercase()), &[obs]);
        }
    }

    let _ = arch;
    let mut result = StageResult::ok(Stage::Model, components_generated, 0, 0);
    result.notes = vec![
        format!("entities: {}", all_entities.join(", ")),
        format!("files: {}", components_generated + 1),
    ];
    Ok(result)
}
