// Stage 5: API — Services → Actix-web endpoint handlers (template-driven)
use tera::Context;
use crate::{GenContext, OrchestratorError, Result};
use super::{Stage, StageResult, write_file};
use isls_blueprint::BlueprintRegistry;

pub fn run(ctx: &mut GenContext, _blueprints: &BlueprintRegistry) -> Result<StageResult> {
    let tera = crate::templates::build_engine()
        .map_err(|e| OrchestratorError::Template(e.to_string()))?;

    let backend_dir = ctx.output_dir.join("backend");
    let mut components_generated = 0;

    // Write api/mod.rs with configure_routes function
    {
        let mut lines = vec![
            "// api/mod.rs — generated by ISLS".to_string(),
            "use actix_web::web;".to_string(),
            String::new(),
        ];
        for module in &ctx.spec.modules {
            lines.push(format!("pub mod {};", module.name));
        }
        lines.push(String::new());
        lines.push("/// Register all API routes.".to_string());
        lines.push("pub fn configure_routes(cfg: &mut web::ServiceConfig) {".to_string());
        for module in &ctx.spec.modules {
            lines.push(format!("    {}::configure(cfg);", module.name));
        }
        lines.push("}".to_string());

        let content = lines.join("\n") + "\n";
        let path = backend_dir.join("src/api/mod.rs");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("api", path.clone(), &bytes);
        ctx.files_written.push(path);
    }

    // One API file per module
    for module in &ctx.spec.modules {
        let mut tctx = Context::new();
        tctx.insert("module", &module.name);
        tctx.insert("entities", &module.entities);
        tctx.insert("app_name", &ctx.spec.name);

        let content = tera.render("api_rs", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;

        let path = backend_dir.join(format!("src/api/{}.rs", module.name));
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("api", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    let mut result = StageResult::ok(Stage::Api, components_generated, 0, components_generated);
    result.notes = vec![
        format!("api modules: {}", ctx.spec.modules.iter().map(|m| m.name.as_str()).collect::<Vec<_>>().join(", ")),
    ];
    Ok(result)
}
