// Stage 3: PERSIST — Models → SQL migrations + database access layer (template-driven, no Oracle)
use tera::Context;
use crate::{GenContext, OrchestratorError, Result};
use super::{Stage, StageResult, write_file};

pub fn run(ctx: &mut GenContext) -> Result<StageResult> {
    let tera = crate::templates::build_engine()
        .map_err(|e| OrchestratorError::Template(e.to_string()))?;

    let backend_dir = ctx.output_dir.join("backend");
    let mut components_generated = 0;

    // Collect all unique entities
    let all_entities: Vec<String> = {
        let mut v: Vec<String> = ctx.spec.modules.iter()
            .flat_map(|m| m.entities.iter().cloned())
            .collect();
        v.sort();
        v.dedup();
        v
    };

    // migrations/001_initial.sql
    {
        let mut tctx = Context::new();
        tctx.insert("app_name", &ctx.spec.name);
        tctx.insert("entities", &all_entities);

        let content = tera.render("migration_sql", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;

        let path = backend_dir.join("migrations/001_initial.sql");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("persist", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    // database/mod.rs
    {
        let mut db_mod_lines = vec!["// database/mod.rs — generated by ISLS".to_string()];
        db_mod_lines.push("pub mod pool;".to_string());
        for module in &ctx.spec.modules {
            db_mod_lines.push(format!("pub mod {}_queries;", module.name));
        }
        let content = db_mod_lines.join("\n") + "\n";
        let path = backend_dir.join("src/database/mod.rs");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("persist", path.clone(), &bytes);
        ctx.files_written.push(path);
    }

    // database/pool.rs
    {
        let mut tctx = Context::new();
        tctx.insert("app_name", &ctx.spec.name);
        let content = tera.render("pool_rs", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;
        let path = backend_dir.join("src/database/pool.rs");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("persist", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    // database/{module}_queries.rs — one per module
    for module in &ctx.spec.modules {
        let mut tctx = Context::new();
        tctx.insert("module", &module.name);
        tctx.insert("entities", &module.entities);
        tctx.insert("app_name", &ctx.spec.name);

        let content = tera.render("queries_rs", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;

        let path = backend_dir.join(format!("src/database/{}_queries.rs", module.name));
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("persist", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    let mut result = StageResult::ok(Stage::Persist, components_generated, 0, 0);
    result.notes = vec![
        format!("migration: migrations/001_initial.sql (tables: {})", all_entities.join(", ")),
        format!("query files: {}", ctx.spec.modules.len()),
    ];
    Ok(result)
}
