// Stage 6: FRONTEND — API → Single-page application (vanilla JS, template-driven)
use tera::Context;
use crate::{GenContext, OrchestratorError, Result};
use super::{Stage, StageResult, write_file};

pub fn run(ctx: &mut GenContext) -> Result<StageResult> {
    let tera = crate::templates::build_engine()
        .map_err(|e| OrchestratorError::Template(e.to_string()))?;

    let frontend_dir = ctx.output_dir.join("frontend");
    let mut components_generated = 0;

    let module_names: Vec<String> = ctx.spec.modules.iter().map(|m| m.name.clone()).collect();

    // index.html
    {
        let mut tctx = Context::new();
        tctx.insert("app_name", &ctx.spec.name);
        tctx.insert("modules", &module_names);
        let content = tera.render("index_html", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;
        let path = frontend_dir.join("index.html");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("frontend", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    // style.css
    {
        let mut tctx = Context::new();
        tctx.insert("app_name", &ctx.spec.name);
        let content = tera.render("style_css", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;
        let path = frontend_dir.join("style.css");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("frontend", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    // src/api/client.js
    {
        let mut tctx = Context::new();
        tctx.insert("app_name", &ctx.spec.name);
        let content = tera.render("client_js", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;
        let path = frontend_dir.join("src/api/client.js");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("frontend", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    // src/app.js
    {
        let mut tctx = Context::new();
        tctx.insert("app_name", &ctx.spec.name);
        tctx.insert("modules", &module_names);
        let content = tera.render("app_js", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;
        let path = frontend_dir.join("src/app.js");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("frontend", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    // dashboard page
    {
        let dashboard_js = format!(
            r#"// Dashboard page — generated by ISLS
export async function render(container) {{
  container.innerHTML = `
    <div class="page">
      <h1>Dashboard — {}</h1>
      <p>Welcome to the {} management system.</p>
      <div class="kpi-cards">
        {}
      </div>
    </div>
  `;
}}
"#,
            ctx.spec.name,
            ctx.spec.name,
            ctx.spec.modules.iter().map(|m| format!(
                r#"<div class="kpi-card"><h3>{}</h3><p><a href="/{}">{} →</a></p></div>"#,
                m.name.to_uppercase(), m.name, m.name
            )).collect::<Vec<_>>().join("\n        ")
        );
        let path = frontend_dir.join("src/pages/dashboard.js");
        let bytes = write_file(&path, &dashboard_js)?;
        ctx.evidence.record("frontend", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    // One page per module
    for module in &ctx.spec.modules {
        let primary_entity = module.entities.first()
            .cloned()
            .unwrap_or_else(|| capitalize(&module.name));

        let mut tctx = Context::new();
        tctx.insert("module", &module.name);
        tctx.insert("primary_entity", &primary_entity);
        tctx.insert("app_name", &ctx.spec.name);

        let content = tera.render("page_js", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;

        let path = frontend_dir.join(format!("src/pages/{}.js", module.name));
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("frontend", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    let mut result = StageResult::ok(Stage::Frontend, components_generated, 0, components_generated);
    result.notes = vec![
        format!("pages: dashboard + {}", module_names.join(", ")),
        "framework: vanilla JS SPA".to_string(),
    ];
    Ok(result)
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().to_string() + c.as_str(),
    }
}
