// Stage 8: DEPLOY — All → Docker, configs, README (template-driven, no Oracle)
use tera::Context;
use crate::{GenContext, OrchestratorError, Result};
use super::{Stage, StageResult, write_file};

pub fn run(ctx: &mut GenContext) -> Result<StageResult> {
    let tera = crate::templates::build_engine()
        .map_err(|e| OrchestratorError::Template(e.to_string()))?;

    let output_dir = ctx.output_dir.clone();
    let backend_dir = output_dir.join("backend");
    let module_names: Vec<String> = ctx.spec.modules.iter().map(|m| m.name.clone()).collect();
    let mut components_generated = 0;

    // backend/Cargo.toml
    {
        let mut tctx = Context::new();
        tctx.insert("app_name", &ctx.spec.name);
        let content = tera.render("backend_cargo_toml", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;
        let path = backend_dir.join("Cargo.toml");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("deploy", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    // backend/src/main.rs
    {
        let mut tctx = Context::new();
        tctx.insert("app_name", &ctx.spec.name);
        tctx.insert("modules", &module_names);
        let content = tera.render("main_rs", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;
        let path = backend_dir.join("src/main.rs");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("deploy", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    // backend/src/config.rs
    {
        let mut tctx = Context::new();
        tctx.insert("app_name", &ctx.spec.name);
        let content = tera.render("config_rs", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;
        let path = backend_dir.join("src/config.rs");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("deploy", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    // backend/src/errors.rs
    {
        let errors_rs = r#"// errors.rs — generated by ISLS
use actix_web::HttpResponse;
use serde_json::json;

#[derive(Debug)]
pub struct AppError(pub String);

impl std::fmt::Display for AppError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl actix_web::ResponseError for AppError {
    fn error_response(&self) -> HttpResponse {
        HttpResponse::InternalServerError().json(json!({"error": self.0}))
    }
}
"#;
        let path = backend_dir.join("src/errors.rs");
        let bytes = write_file(&path, errors_rs)?;
        ctx.evidence.record("deploy", path.clone(), &bytes);
        ctx.files_written.push(path);
    }

    // backend/Dockerfile
    {
        let mut tctx = Context::new();
        tctx.insert("app_name", &ctx.spec.name);
        let content = tera.render("dockerfile_backend", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;
        let path = backend_dir.join("Dockerfile");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("deploy", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    // docker-compose.yml
    {
        let mut tctx = Context::new();
        tctx.insert("app_name", &ctx.spec.name);
        let content = tera.render("docker_compose", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;
        let path = output_dir.join("docker-compose.yml");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("deploy", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    // .env.example
    {
        let mut tctx = Context::new();
        tctx.insert("app_name", &ctx.spec.name);
        let content = tera.render("env_example", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;
        let path = output_dir.join(".env.example");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("deploy", path.clone(), &bytes);
        ctx.files_written.push(path);
    }

    // .gitignore
    {
        let mut tctx = Context::new();
        tctx.insert("app_name", &ctx.spec.name);
        let content = tera.render("gitignore", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;
        let path = output_dir.join(".gitignore");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("deploy", path.clone(), &bytes);
        ctx.files_written.push(path);
    }

    // README.md
    {
        let mut tctx = Context::new();
        tctx.insert("app_name", &ctx.spec.name);
        tctx.insert("modules", &module_names);
        let content = tera.render("readme_md", &tctx)
            .map_err(|e| OrchestratorError::Template(e.to_string()))?;
        let path = output_dir.join("README.md");
        let bytes = write_file(&path, &content)?;
        ctx.evidence.record("deploy", path.clone(), &bytes);
        ctx.files_written.push(path);
        components_generated += 1;
    }

    let mut result = StageResult::ok(Stage::Deploy, components_generated, 0, 0);
    result.notes = vec![
        "docker-compose.yml, Dockerfile, .env.example, .gitignore, README.md".to_string(),
    ];
    Ok(result)
}
