// Copyright (c) 2026 Sebastian Klemm
// SPDX-License-Identifier: MIT
//
//! ISLS v3.1 — Template-Free LLM Generation Engine.
//!
//! Replaces Tera-template emission with an LLM-driven, compile-verified
//! pipeline.  Every file is generated by an LLM whose prompt includes ALL
//! types produced so far (the *growing TypeContext*), eliminating hallucinated
//! field names.
//!
//! # Pipeline
//! ```text
//! AppSpec  →  LlmForge::generate()
//!   Layer 0: static files (Cargo.toml, docker-compose.yml, Dockerfile, …)
//!   Layer 1: Foundation (errors.rs, config.rs, pagination.rs)
//!   Layer 2: Auth (models/user.rs, auth.rs)
//!   Layer 3: Models ({entity}.rs)
//!   Layer 4: Database (migrations, queries, pool)
//!   Layer 5: Services ({entity}.rs)
//!   Layer 6: API ({entity}.rs, auth_routes.rs)
//!   Layer 7: main.rs
//!   Layer 8: Frontend (index.html, CSS, JS)
//!   Layer 9: Tests (api_tests.rs)
//! ```
//!
//! # Example
//! ```rust,ignore
//! use isls_forge_llm::{LlmForge, ForgePlan, AppSpec};
//! use isls_forge_llm::oracle::MockOracle;
//!
//! let oracle = Box::new(MockOracle);
//! let plan = ForgePlan::warehouse_default("warehouse-app");
//! let mut forge = LlmForge::new(oracle, plan, "/tmp/out".into(), true);
//! let files = forge.generate().unwrap();
//! ```

pub mod forge;
pub mod hdag;
pub mod mock;
pub mod oracle;
pub mod order;
pub mod prompt;
pub mod provided;
pub mod staged_closure;
pub mod static_files;
pub mod structural;
pub mod type_context;

pub use forge::{ForgeLlmError, LlmForge, Result};
pub use oracle::{estimate_tokens, MockOracle, OpenAiOracle, Oracle};
pub use type_context::TypeContext;

use isls_hypercube::domain::FieldDef;
use serde::{Deserialize, Serialize};

// ─── EntityDef ────────────────────────────────────────────────────────────────

/// A domain entity definition used by the forge pipeline.
///
/// Populated from the domain registry's `EntityTemplate` plus optional
/// business-rule annotations.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EntityDef {
    /// Entity name in PascalCase (e.g. `"Product"`).
    pub name: String,
    /// Entity name in snake_case (e.g. `"product"`).
    pub snake_name: String,
    /// All entity fields including id and timestamps.
    pub fields: Vec<FieldDef>,
    /// Validation rules expressed as Rust boolean conditions.
    pub validations: Vec<ValidationRule>,
    /// Business rules driving the service layer.
    pub business_rules: Vec<String>,
    /// Related entities (for join/FK awareness in prompts).
    pub relationships: Vec<String>,
}

/// A simple validation rule (maps to `if !{condition} { errors.push({message}) }`).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ValidationRule {
    /// Rust boolean expression on `self` (e.g. `"!self.sku.is_empty()"`).
    pub condition: String,
    /// Error message emitted when the condition is false.
    pub message: String,
}

// ─── AppSpec ──────────────────────────────────────────────────────────────────

/// High-level application specification derived from the requirements TOML.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AppSpec {
    /// Application name (kebab-case, e.g. `"warehouse-app"`).
    pub app_name: String,
    /// Human-readable description injected into LLM prompts.
    pub description: String,
    /// Domain name (e.g. `"warehouse"`).
    pub domain_name: String,
    /// All entities in the application.
    pub entities: Vec<EntityDef>,
    /// Top-level business rules (cross-entity).
    pub business_rules: Vec<String>,
}

impl AppSpec {
    /// snake_case version of `app_name`.
    pub fn app_name_snake(&self) -> String {
        self.app_name.replace('-', "_")
    }

    /// All entity snake_names.
    pub fn entity_snakes(&self) -> Vec<String> {
        self.entities.iter().map(|e| e.snake_name.clone()).collect()
    }
}

// ─── ForgePlan ────────────────────────────────────────────────────────────────

/// The complete forge plan: application spec plus which norm IDs contributed.
#[derive(Clone, Debug)]
pub struct ForgePlan {
    /// Application specification.
    pub spec: AppSpec,
    /// Norm IDs that this plan was composed from.
    pub norm_ids: Vec<String>,
}

impl ForgePlan {
    /// Build a `ForgePlan` from an `AppSpec` and a list of norm IDs.
    pub fn new(spec: AppSpec, norm_ids: Vec<String>) -> Self {
        Self { spec, norm_ids }
    }

    /// Create a minimal warehouse plan for testing / mock mode.
    ///
    /// Uses the warehouse entity definitions from the domain registry.
    pub fn warehouse_default(app_name: &str) -> Self {
        use isls_hypercube::domain::{DomainRegistry, FieldDef};

        let registry = DomainRegistry::new();
        let toml_hint = "warehouse inventory management stock orders";
        let domain = registry
            .detect(toml_hint)
            .cloned()
            .unwrap_or_else(|| minimal_warehouse_domain(app_name));

        let entities: Vec<EntityDef> = domain
            .entities
            .iter()
            .map(|et| EntityDef {
                name: et.name.clone(),
                snake_name: to_snake_case(&et.name),
                fields: et.fields.clone(),
                validations: et
                    .validations
                    .iter()
                    .map(|v| ValidationRule {
                        condition: v.condition.clone(),
                        message: v.message.clone(),
                    })
                    .collect(),
                business_rules: Vec::new(),
                relationships: Vec::new(),
            })
            .collect();

        let business_rules: Vec<String> = domain
            .business_rules
            .iter()
            .map(|r| format!("{}: {}", r.name, r.description))
            .collect();

        let spec = AppSpec {
            app_name: app_name.to_string(),
            description: format!(
                "A warehouse management system with inventory tracking, \
                 order management, and reporting."
            ),
            domain_name: domain.name.clone(),
            entities,
            business_rules,
        };

        Self {
            spec,
            norm_ids: vec![
                "ISLS-NORM-0042".into(), // CRUD-Entity
                "ISLS-NORM-0088".into(), // JWT-Auth
                "ISLS-NORM-0096".into(), // Pagination
                "ISLS-NORM-0103".into(), // ErrorSystem
                "ISLS-NORM-0500".into(), // Warehouse organism
            ],
        }
    }

    /// Build a `ForgePlan` dynamically from a [`ComposedPlan`] (v3.2 wiring).
    ///
    /// Converts composed norm artifacts into `EntityDef`s and an `AppSpec`,
    /// replacing the hardcoded `warehouse_default()` approach with a
    /// domain-agnostic plan builder.
    ///
    /// If no User-like entity exists in the composed plan, a standard User
    /// entity is injected for JWT authentication support.
    pub fn from_composed_plan(
        app_name: &str,
        description: &str,
        plan: &isls_norms::composition::ComposedPlan,
    ) -> Self {
        use isls_hypercube::domain::FieldDef;

        let mut entities: Vec<EntityDef> = plan.models.iter().map(|model| {
            let fields: Vec<FieldDef> = model.fields.iter().map(|f| FieldDef {
                name: f.name.clone(),
                rust_type: f.rust_type.clone(),
                sql_type: f.sql_type.clone(),
                nullable: f.nullable,
                default_value: f.default_value.clone(),
                description: f.description.clone(),
            }).collect();

            let validations: Vec<ValidationRule> = model.validations.iter().map(|v| {
                ValidationRule {
                    condition: v.condition.clone(),
                    message: v.message.clone(),
                }
            }).collect();

            // Collect business rules from matching services
            let snake = to_snake_case(&model.struct_name);
            let business_rules: Vec<String> = plan.services.iter()
                .filter(|s| s.name.to_lowercase().contains(&snake))
                .flat_map(|s| s.business_rules.iter().cloned())
                .collect();

            // Collect relationships from interfaces
            let relationships: Vec<String> = plan.interfaces.iter()
                .filter(|iface| iface.description.contains(&model.struct_name) || iface.types_shared.iter().any(|t| t.contains(&model.struct_name)))
                .map(|iface| iface.description.clone())
                .collect();

            EntityDef {
                name: model.struct_name.clone(),
                snake_name: snake,
                fields,
                validations,
                business_rules,
                relationships,
            }
        }).collect();

        // Standard User entity injection: if no User-like entity exists, inject one
        let has_user = entities.iter().any(|e| {
            let lower = e.name.to_lowercase();
            lower == "user" || lower == "account" || lower == "admin"
        });
        if !has_user {
            entities.push(standard_user_entity());
        }

        // Collect top-level business rules from services
        let business_rules: Vec<String> = plan.services.iter()
            .flat_map(|s| s.business_rules.iter().cloned())
            .collect();

        // Infer domain name from app name
        let domain_name = app_name.replace('-', " ")
            .split_whitespace()
            .next()
            .unwrap_or("app")
            .to_string();

        let spec = AppSpec {
            app_name: app_name.to_string(),
            description: description.to_string(),
            domain_name,
            entities,
            business_rules,
        };

        Self {
            spec,
            norm_ids: plan.contributing_norms.clone(),
        }
    }

    /// Build a `ForgePlan` from a domain template (detected from TOML).
    pub fn from_domain(
        app_name: &str,
        description: &str,
        domain: &isls_hypercube::domain::DomainTemplate,
    ) -> Self {
        let entities: Vec<EntityDef> = domain
            .entities
            .iter()
            .map(|et| EntityDef {
                name: et.name.clone(),
                snake_name: to_snake_case(&et.name),
                fields: et.fields.clone(),
                validations: et
                    .validations
                    .iter()
                    .map(|v| ValidationRule {
                        condition: v.condition.clone(),
                        message: v.message.clone(),
                    })
                    .collect(),
                business_rules: Vec::new(),
                relationships: Vec::new(),
            })
            .collect();

        let business_rules: Vec<String> = domain
            .business_rules
            .iter()
            .map(|r| format!("{}: {}", r.name, r.description))
            .collect();

        let spec = AppSpec {
            app_name: app_name.to_string(),
            description: description.to_string(),
            domain_name: domain.name.clone(),
            entities,
            business_rules,
        };

        Self {
            spec,
            norm_ids: vec![
                "ISLS-NORM-0042".into(),
                "ISLS-NORM-0088".into(),
                "ISLS-NORM-0096".into(),
                "ISLS-NORM-0103".into(),
                "ISLS-NORM-0500".into(),
            ],
        }
    }
}

// ─── FileSpec ─────────────────────────────────────────────────────────────────

/// Specification for a single file to be generated.
#[derive(Clone, Debug)]
pub struct FileSpec {
    /// Relative path within the output directory (e.g. `"backend/src/errors.rs"`).
    pub path: String,
    /// Generation layer (0 = static, 1-9 = LLM layers).
    pub layer: u8,
    /// Entity this file primarily serves (if applicable).
    pub entity: Option<String>,
    /// Brief purpose description for the prompt.
    pub purpose: String,
    /// Whether this is a Rust source file (triggers `cargo check` after generation).
    pub is_rust: bool,
    /// How to generate this file.
    pub method: GenerationMethod,
}

/// How a file should be generated.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum GenerationMethod {
    /// Pure string-building (Cargo.toml, Dockerfile, etc.).
    Static,
    /// Rust function builds code string from norm data (no LLM).
    Mock,
    /// LLM call with growing TypeContext + retry loop.
    Llm,
}

// ─── GeneratedFile ────────────────────────────────────────────────────────────

/// A file that has been generated by the forge.
#[derive(Clone, Debug)]
pub struct GeneratedFile {
    /// Relative path within the output directory.
    pub path: String,
    /// File content.
    pub content: String,
    /// How the file was generated (`"static"`, `"mock"`, or `"llm"`).
    pub generation_method: String,
    /// Number of generation attempts (1 on first success, up to 3 on retry).
    pub attempts: u32,
    /// Estimated tokens used for this file's generation.
    pub tokens_used: u64,
}

// ─── ForgeStats ───────────────────────────────────────────────────────────────

/// Statistics accumulated during a forge run.
#[derive(Clone, Debug, Default)]
pub struct ForgeStats {
    /// Total number of files generated.
    pub files_generated: usize,
    /// Total estimated tokens consumed by LLM calls.
    pub total_tokens: u64,
    /// Number of `cargo check` invocations.
    pub compile_checks: usize,
    /// Number of failed `cargo check` invocations.
    pub compile_failures: usize,
    /// Total retry count across all files.
    pub retries: usize,
    /// Wall-clock time for the full generation run.
    pub total_time_secs: f64,
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

/// Convert PascalCase to snake_case.
pub fn to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.char_indices() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.extend(ch.to_lowercase());
    }
    out
}

/// Build a standard User entity for authentication when no User-like entity
/// exists in the composed plan.
fn standard_user_entity() -> EntityDef {
    use isls_hypercube::domain::FieldDef;
    EntityDef {
        name: "User".to_string(),
        snake_name: "user".to_string(),
        fields: vec![
            FieldDef { name: "id".into(), rust_type: "i64".into(), sql_type: "BIGSERIAL PRIMARY KEY".into(), nullable: false, default_value: None, description: "Primary key".into() },
            FieldDef { name: "email".into(), rust_type: "String".into(), sql_type: "VARCHAR(255) UNIQUE NOT NULL".into(), nullable: false, default_value: None, description: "User email address".into() },
            FieldDef { name: "password_hash".into(), rust_type: "String".into(), sql_type: "VARCHAR(255) NOT NULL".into(), nullable: false, default_value: None, description: "Bcrypt password hash".into() },
            FieldDef { name: "role".into(), rust_type: "String".into(), sql_type: "VARCHAR(50) NOT NULL DEFAULT 'user'".into(), nullable: false, default_value: Some("'user'".into()), description: "User role (admin, manager, user)".into() },
            FieldDef { name: "is_active".into(), rust_type: "bool".into(), sql_type: "BOOLEAN NOT NULL DEFAULT true".into(), nullable: false, default_value: Some("true".into()), description: "Account active flag".into() },
            FieldDef { name: "created_at".into(), rust_type: "String".into(), sql_type: "TIMESTAMPTZ NOT NULL DEFAULT NOW()".into(), nullable: false, default_value: Some("NOW()".into()), description: "Account creation timestamp".into() },
            FieldDef { name: "updated_at".into(), rust_type: "String".into(), sql_type: "TIMESTAMPTZ NOT NULL DEFAULT NOW()".into(), nullable: false, default_value: Some("NOW()".into()), description: "Last update timestamp".into() },
        ],
        validations: vec![
            ValidationRule { condition: "!self.email.is_empty()".into(), message: "Email must not be empty".into() },
            ValidationRule { condition: "self.email.contains('@')".into(), message: "Email must contain @".into() },
        ],
        business_rules: vec!["Password must be hashed before storage".into()],
        relationships: vec!["Referenced by all authenticated endpoints".into()],
    }
}

/// Build a minimal warehouse domain when the registry cannot detect it.
fn minimal_warehouse_domain(
    _app_name: &str,
) -> isls_hypercube::domain::DomainTemplate {
    use isls_hypercube::domain::{ApiFeatures, BusinessRule, DomainTemplate};
    DomainTemplate {
        name: "warehouse".into(),
        keywords: vec!["warehouse".into(), "inventory".into(), "stock".into()],
        entities: vec![],
        relationships: vec![],
        business_rules: vec![],
        api_features: ApiFeatures {
            pagination: true,
            filtering: vec![],
            sorting: vec!["created_at".into()],
            search_fields: vec!["name".into()],
            export_formats: vec!["json".into()],
        },
    }
}
