// Copyright (c) 2026 Sebastian Klemm
// SPDX-License-Identifier: MIT
//
//! ISLS v3.1 — Template-Free LLM Generation Engine.
//!
//! Replaces Tera-template emission with an LLM-driven, compile-verified
//! pipeline.  Every file is generated by an LLM whose prompt includes ALL
//! types produced so far (the *growing TypeContext*), eliminating hallucinated
//! field names.
//!
//! # Pipeline
//! ```text
//! AppSpec  →  LlmForge::generate()
//!   Layer 0: static files (Cargo.toml, docker-compose.yml, Dockerfile, …)
//!   Layer 1: Foundation (errors.rs, config.rs, pagination.rs)
//!   Layer 2: Auth (models/user.rs, auth.rs)
//!   Layer 3: Models ({entity}.rs)
//!   Layer 4: Database (migrations, queries, pool)
//!   Layer 5: Services ({entity}.rs)
//!   Layer 6: API ({entity}.rs, auth_routes.rs)
//!   Layer 7: main.rs
//!   Layer 8: Frontend (index.html, CSS, JS)
//!   Layer 9: Tests (api_tests.rs)
//! ```
//!
//! # Example
//! ```rust,ignore
//! use isls_forge_llm::{LlmForge, ForgePlan, AppSpec};
//! use isls_renderloop::MockOracle;
//!
//! let oracle = Box::new(MockOracle);
//! let plan = ForgePlan::warehouse_default("warehouse-app");
//! let mut forge = LlmForge::new(oracle, plan, "/tmp/out".into(), true);
//! let files = forge.generate().unwrap();
//! ```

pub mod forge;
pub mod mock;
pub mod order;
pub mod prompt;
pub mod static_files;

pub use forge::{ForgeLlmError, LlmForge, Result};

use isls_hypercube::domain::FieldDef;
use serde::{Deserialize, Serialize};

// ─── EntityDef ────────────────────────────────────────────────────────────────

/// A domain entity definition used by the forge pipeline.
///
/// Populated from the domain registry's `EntityTemplate` plus optional
/// business-rule annotations.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EntityDef {
    /// Entity name in PascalCase (e.g. `"Product"`).
    pub name: String,
    /// Entity name in snake_case (e.g. `"product"`).
    pub snake_name: String,
    /// All entity fields including id and timestamps.
    pub fields: Vec<FieldDef>,
    /// Validation rules expressed as Rust boolean conditions.
    pub validations: Vec<ValidationRule>,
    /// Business rules driving the service layer.
    pub business_rules: Vec<String>,
    /// Related entities (for join/FK awareness in prompts).
    pub relationships: Vec<String>,
}

/// A simple validation rule (maps to `if !{condition} { errors.push({message}) }`).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ValidationRule {
    /// Rust boolean expression on `self` (e.g. `"!self.sku.is_empty()"`).
    pub condition: String,
    /// Error message emitted when the condition is false.
    pub message: String,
}

// ─── AppSpec ──────────────────────────────────────────────────────────────────

/// High-level application specification derived from the requirements TOML.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AppSpec {
    /// Application name (kebab-case, e.g. `"warehouse-app"`).
    pub app_name: String,
    /// Human-readable description injected into LLM prompts.
    pub description: String,
    /// Domain name (e.g. `"warehouse"`).
    pub domain_name: String,
    /// All entities in the application.
    pub entities: Vec<EntityDef>,
    /// Top-level business rules (cross-entity).
    pub business_rules: Vec<String>,
}

impl AppSpec {
    /// snake_case version of `app_name`.
    pub fn app_name_snake(&self) -> String {
        self.app_name.replace('-', "_")
    }

    /// All entity snake_names.
    pub fn entity_snakes(&self) -> Vec<String> {
        self.entities.iter().map(|e| e.snake_name.clone()).collect()
    }
}

// ─── ForgePlan ────────────────────────────────────────────────────────────────

/// The complete forge plan: application spec plus which norm IDs contributed.
#[derive(Clone, Debug)]
pub struct ForgePlan {
    /// Application specification.
    pub spec: AppSpec,
    /// Norm IDs that this plan was composed from.
    pub norm_ids: Vec<String>,
}

impl ForgePlan {
    /// Build a `ForgePlan` from an `AppSpec` and a list of norm IDs.
    pub fn new(spec: AppSpec, norm_ids: Vec<String>) -> Self {
        Self { spec, norm_ids }
    }

    /// Create a minimal warehouse plan for testing / mock mode.
    ///
    /// Uses the warehouse entity definitions from the domain registry.
    pub fn warehouse_default(app_name: &str) -> Self {
        use isls_hypercube::domain::{DomainRegistry, FieldDef};

        let registry = DomainRegistry::new();
        let toml_hint = "warehouse inventory management stock orders";
        let domain = registry
            .detect(toml_hint)
            .cloned()
            .unwrap_or_else(|| minimal_warehouse_domain(app_name));

        let entities: Vec<EntityDef> = domain
            .entities
            .iter()
            .map(|et| EntityDef {
                name: et.name.clone(),
                snake_name: to_snake_case(&et.name),
                fields: et.fields.clone(),
                validations: et
                    .validations
                    .iter()
                    .map(|v| ValidationRule {
                        condition: v.condition.clone(),
                        message: v.message.clone(),
                    })
                    .collect(),
                business_rules: Vec::new(),
                relationships: Vec::new(),
            })
            .collect();

        let business_rules: Vec<String> = domain
            .business_rules
            .iter()
            .map(|r| format!("{}: {}", r.name, r.description))
            .collect();

        let spec = AppSpec {
            app_name: app_name.to_string(),
            description: format!(
                "A warehouse management system with inventory tracking, \
                 order management, and reporting."
            ),
            domain_name: domain.name.clone(),
            entities,
            business_rules,
        };

        Self {
            spec,
            norm_ids: vec![
                "ISLS-NORM-0042".into(), // CRUD-Entity
                "ISLS-NORM-0088".into(), // JWT-Auth
                "ISLS-NORM-0096".into(), // Pagination
                "ISLS-NORM-0103".into(), // ErrorSystem
                "ISLS-NORM-0500".into(), // Warehouse organism
            ],
        }
    }

    /// Build a `ForgePlan` from a domain template (detected from TOML).
    pub fn from_domain(
        app_name: &str,
        description: &str,
        domain: &isls_hypercube::domain::DomainTemplate,
    ) -> Self {
        let entities: Vec<EntityDef> = domain
            .entities
            .iter()
            .map(|et| EntityDef {
                name: et.name.clone(),
                snake_name: to_snake_case(&et.name),
                fields: et.fields.clone(),
                validations: et
                    .validations
                    .iter()
                    .map(|v| ValidationRule {
                        condition: v.condition.clone(),
                        message: v.message.clone(),
                    })
                    .collect(),
                business_rules: Vec::new(),
                relationships: Vec::new(),
            })
            .collect();

        let business_rules: Vec<String> = domain
            .business_rules
            .iter()
            .map(|r| format!("{}: {}", r.name, r.description))
            .collect();

        let spec = AppSpec {
            app_name: app_name.to_string(),
            description: description.to_string(),
            domain_name: domain.name.clone(),
            entities,
            business_rules,
        };

        Self {
            spec,
            norm_ids: vec![
                "ISLS-NORM-0042".into(),
                "ISLS-NORM-0088".into(),
                "ISLS-NORM-0096".into(),
                "ISLS-NORM-0103".into(),
                "ISLS-NORM-0500".into(),
            ],
        }
    }
}

// ─── FileSpec ─────────────────────────────────────────────────────────────────

/// Specification for a single file to be generated.
#[derive(Clone, Debug)]
pub struct FileSpec {
    /// Relative path within the output directory (e.g. `"backend/src/errors.rs"`).
    pub path: String,
    /// Generation layer (0 = static, 1-9 = LLM layers).
    pub layer: u8,
    /// Entity this file primarily serves (if applicable).
    pub entity: Option<String>,
    /// Brief purpose description for the prompt.
    pub purpose: String,
    /// Whether this is a Rust source file (triggers `cargo check` after generation).
    pub is_rust: bool,
    /// How to generate this file.
    pub method: GenerationMethod,
}

/// How a file should be generated.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum GenerationMethod {
    /// Pure string-building (Cargo.toml, Dockerfile, etc.).
    Static,
    /// Rust function builds code string from norm data (no LLM).
    Mock,
    /// LLM call with growing TypeContext + retry loop.
    Llm,
}

// ─── GeneratedFile ────────────────────────────────────────────────────────────

/// A file that has been generated by the forge.
#[derive(Clone, Debug)]
pub struct GeneratedFile {
    /// Relative path within the output directory.
    pub path: String,
    /// File content.
    pub content: String,
    /// How the file was generated (`"static"`, `"mock"`, or `"llm"`).
    pub generation_method: String,
    /// Number of generation attempts (1 on first success, up to 3 on retry).
    pub attempts: u32,
    /// Estimated tokens used for this file's generation.
    pub tokens_used: u64,
}

// ─── ForgeStats ───────────────────────────────────────────────────────────────

/// Statistics accumulated during a forge run.
#[derive(Clone, Debug, Default)]
pub struct ForgeStats {
    /// Total number of files generated.
    pub files_generated: usize,
    /// Total estimated tokens consumed by LLM calls.
    pub total_tokens: u64,
    /// Number of `cargo check` invocations.
    pub compile_checks: usize,
    /// Number of failed `cargo check` invocations.
    pub compile_failures: usize,
    /// Total retry count across all files.
    pub retries: usize,
    /// Wall-clock time for the full generation run.
    pub total_time_secs: f64,
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

/// Convert PascalCase to snake_case.
pub fn to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.char_indices() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.extend(ch.to_lowercase());
    }
    out
}

/// Build a minimal warehouse domain when the registry cannot detect it.
fn minimal_warehouse_domain(
    _app_name: &str,
) -> isls_hypercube::domain::DomainTemplate {
    use isls_hypercube::domain::{ApiFeatures, BusinessRule, DomainTemplate};
    DomainTemplate {
        name: "warehouse".into(),
        keywords: vec!["warehouse".into(), "inventory".into(), "stock".into()],
        entities: vec![],
        relationships: vec![],
        business_rules: vec![],
        api_features: ApiFeatures {
            pagination: true,
            filtering: vec![],
            sorting: vec!["created_at".into()],
            search_fields: vec!["name".into()],
            export_formats: vec!["json".into()],
        },
    }
}
